#[mcp_servers.cloudflare]
#url = "https://mcp.cloudflare.com/mcp"

#[mcp_servers.skills-dev]
#url = "https://skill.dev.haak.co:8443/mcp"

[mcp_servers.playwright]
args = ["@playwright/mcp@latest"]
command = "npx"

[mcp_servers.codegraph]
command ="codegraph"
args = [ "serve","--mcp"]

