// Code generated by ent, DO NOT EDIT.

package _test

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/haakco/mcp-kit/entschema/_test/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/haakco/mcp-kit/entschema/_test/oauthaccesstoken"
	"github.com/haakco/mcp-kit/entschema/_test/oauthauthorizationcode"
	"github.com/haakco/mcp-kit/entschema/_test/oauthclient"
	"github.com/haakco/mcp-kit/entschema/_test/oauthrefreshtoken"
	"github.com/haakco/mcp-kit/entschema/_test/oauthsigningkey"
	"github.com/haakco/mcp-kit/entschema/_test/personalaccesstoken"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// OAuthAccessToken is the client for interacting with the OAuthAccessToken builders.
	OAuthAccessToken *OAuthAccessTokenClient
	// OAuthAuthorizationCode is the client for interacting with the OAuthAuthorizationCode builders.
	OAuthAuthorizationCode *OAuthAuthorizationCodeClient
	// OAuthClient is the client for interacting with the OAuthClient builders.
	OAuthClient *OAuthClientClient
	// OAuthRefreshToken is the client for interacting with the OAuthRefreshToken builders.
	OAuthRefreshToken *OAuthRefreshTokenClient
	// OAuthSigningKey is the client for interacting with the OAuthSigningKey builders.
	OAuthSigningKey *OAuthSigningKeyClient
	// PersonalAccessToken is the client for interacting with the PersonalAccessToken builders.
	PersonalAccessToken *PersonalAccessTokenClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.OAuthAccessToken = NewOAuthAccessTokenClient(c.config)
	c.OAuthAuthorizationCode = NewOAuthAuthorizationCodeClient(c.config)
	c.OAuthClient = NewOAuthClientClient(c.config)
	c.OAuthRefreshToken = NewOAuthRefreshTokenClient(c.config)
	c.OAuthSigningKey = NewOAuthSigningKeyClient(c.config)
	c.PersonalAccessToken = NewPersonalAccessTokenClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("_test: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("_test: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                    ctx,
		config:                 cfg,
		OAuthAccessToken:       NewOAuthAccessTokenClient(cfg),
		OAuthAuthorizationCode: NewOAuthAuthorizationCodeClient(cfg),
		OAuthClient:            NewOAuthClientClient(cfg),
		OAuthRefreshToken:      NewOAuthRefreshTokenClient(cfg),
		OAuthSigningKey:        NewOAuthSigningKeyClient(cfg),
		PersonalAccessToken:    NewPersonalAccessTokenClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                    ctx,
		config:                 cfg,
		OAuthAccessToken:       NewOAuthAccessTokenClient(cfg),
		OAuthAuthorizationCode: NewOAuthAuthorizationCodeClient(cfg),
		OAuthClient:            NewOAuthClientClient(cfg),
		OAuthRefreshToken:      NewOAuthRefreshTokenClient(cfg),
		OAuthSigningKey:        NewOAuthSigningKeyClient(cfg),
		PersonalAccessToken:    NewPersonalAccessTokenClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		OAuthAccessToken.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.OAuthAccessToken, c.OAuthAuthorizationCode, c.OAuthClient,
		c.OAuthRefreshToken, c.OAuthSigningKey, c.PersonalAccessToken,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.OAuthAccessToken, c.OAuthAuthorizationCode, c.OAuthClient,
		c.OAuthRefreshToken, c.OAuthSigningKey, c.PersonalAccessToken,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *OAuthAccessTokenMutation:
		return c.OAuthAccessToken.mutate(ctx, m)
	case *OAuthAuthorizationCodeMutation:
		return c.OAuthAuthorizationCode.mutate(ctx, m)
	case *OAuthClientMutation:
		return c.OAuthClient.mutate(ctx, m)
	case *OAuthRefreshTokenMutation:
		return c.OAuthRefreshToken.mutate(ctx, m)
	case *OAuthSigningKeyMutation:
		return c.OAuthSigningKey.mutate(ctx, m)
	case *PersonalAccessTokenMutation:
		return c.PersonalAccessToken.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("_test: unknown mutation type %T", m)
	}
}

// OAuthAccessTokenClient is a client for the OAuthAccessToken schema.
type OAuthAccessTokenClient struct {
	config
}

// NewOAuthAccessTokenClient returns a client for the OAuthAccessToken from the given config.
func NewOAuthAccessTokenClient(c config) *OAuthAccessTokenClient {
	return &OAuthAccessTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `oauthaccesstoken.Hooks(f(g(h())))`.
func (c *OAuthAccessTokenClient) Use(hooks ...Hook) {
	c.hooks.OAuthAccessToken = append(c.hooks.OAuthAccessToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `oauthaccesstoken.Intercept(f(g(h())))`.
func (c *OAuthAccessTokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.OAuthAccessToken = append(c.inters.OAuthAccessToken, interceptors...)
}

// Create returns a builder for creating a OAuthAccessToken entity.
func (c *OAuthAccessTokenClient) Create() *OAuthAccessTokenCreate {
	mutation := newOAuthAccessTokenMutation(c.config, OpCreate)
	return &OAuthAccessTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OAuthAccessToken entities.
func (c *OAuthAccessTokenClient) CreateBulk(builders ...*OAuthAccessTokenCreate) *OAuthAccessTokenCreateBulk {
	return &OAuthAccessTokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OAuthAccessTokenClient) MapCreateBulk(slice any, setFunc func(*OAuthAccessTokenCreate, int)) *OAuthAccessTokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OAuthAccessTokenCreateBulk{err: fmt.Errorf("calling to OAuthAccessTokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OAuthAccessTokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OAuthAccessTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OAuthAccessToken.
func (c *OAuthAccessTokenClient) Update() *OAuthAccessTokenUpdate {
	mutation := newOAuthAccessTokenMutation(c.config, OpUpdate)
	return &OAuthAccessTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OAuthAccessTokenClient) UpdateOne(_m *OAuthAccessToken) *OAuthAccessTokenUpdateOne {
	mutation := newOAuthAccessTokenMutation(c.config, OpUpdateOne, withOAuthAccessToken(_m))
	return &OAuthAccessTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OAuthAccessTokenClient) UpdateOneID(id int) *OAuthAccessTokenUpdateOne {
	mutation := newOAuthAccessTokenMutation(c.config, OpUpdateOne, withOAuthAccessTokenID(id))
	return &OAuthAccessTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OAuthAccessToken.
func (c *OAuthAccessTokenClient) Delete() *OAuthAccessTokenDelete {
	mutation := newOAuthAccessTokenMutation(c.config, OpDelete)
	return &OAuthAccessTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OAuthAccessTokenClient) DeleteOne(_m *OAuthAccessToken) *OAuthAccessTokenDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OAuthAccessTokenClient) DeleteOneID(id int) *OAuthAccessTokenDeleteOne {
	builder := c.Delete().Where(oauthaccesstoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OAuthAccessTokenDeleteOne{builder}
}

// Query returns a query builder for OAuthAccessToken.
func (c *OAuthAccessTokenClient) Query() *OAuthAccessTokenQuery {
	return &OAuthAccessTokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOAuthAccessToken},
		inters: c.Interceptors(),
	}
}

// Get returns a OAuthAccessToken entity by its id.
func (c *OAuthAccessTokenClient) Get(ctx context.Context, id int) (*OAuthAccessToken, error) {
	return c.Query().Where(oauthaccesstoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OAuthAccessTokenClient) GetX(ctx context.Context, id int) *OAuthAccessToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OAuthAccessTokenClient) Hooks() []Hook {
	return c.hooks.OAuthAccessToken
}

// Interceptors returns the client interceptors.
func (c *OAuthAccessTokenClient) Interceptors() []Interceptor {
	return c.inters.OAuthAccessToken
}

func (c *OAuthAccessTokenClient) mutate(ctx context.Context, m *OAuthAccessTokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OAuthAccessTokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OAuthAccessTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OAuthAccessTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OAuthAccessTokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("_test: unknown OAuthAccessToken mutation op: %q", m.Op())
	}
}

// OAuthAuthorizationCodeClient is a client for the OAuthAuthorizationCode schema.
type OAuthAuthorizationCodeClient struct {
	config
}

// NewOAuthAuthorizationCodeClient returns a client for the OAuthAuthorizationCode from the given config.
func NewOAuthAuthorizationCodeClient(c config) *OAuthAuthorizationCodeClient {
	return &OAuthAuthorizationCodeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `oauthauthorizationcode.Hooks(f(g(h())))`.
func (c *OAuthAuthorizationCodeClient) Use(hooks ...Hook) {
	c.hooks.OAuthAuthorizationCode = append(c.hooks.OAuthAuthorizationCode, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `oauthauthorizationcode.Intercept(f(g(h())))`.
func (c *OAuthAuthorizationCodeClient) Intercept(interceptors ...Interceptor) {
	c.inters.OAuthAuthorizationCode = append(c.inters.OAuthAuthorizationCode, interceptors...)
}

// Create returns a builder for creating a OAuthAuthorizationCode entity.
func (c *OAuthAuthorizationCodeClient) Create() *OAuthAuthorizationCodeCreate {
	mutation := newOAuthAuthorizationCodeMutation(c.config, OpCreate)
	return &OAuthAuthorizationCodeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OAuthAuthorizationCode entities.
func (c *OAuthAuthorizationCodeClient) CreateBulk(builders ...*OAuthAuthorizationCodeCreate) *OAuthAuthorizationCodeCreateBulk {
	return &OAuthAuthorizationCodeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OAuthAuthorizationCodeClient) MapCreateBulk(slice any, setFunc func(*OAuthAuthorizationCodeCreate, int)) *OAuthAuthorizationCodeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OAuthAuthorizationCodeCreateBulk{err: fmt.Errorf("calling to OAuthAuthorizationCodeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OAuthAuthorizationCodeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OAuthAuthorizationCodeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OAuthAuthorizationCode.
func (c *OAuthAuthorizationCodeClient) Update() *OAuthAuthorizationCodeUpdate {
	mutation := newOAuthAuthorizationCodeMutation(c.config, OpUpdate)
	return &OAuthAuthorizationCodeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OAuthAuthorizationCodeClient) UpdateOne(_m *OAuthAuthorizationCode) *OAuthAuthorizationCodeUpdateOne {
	mutation := newOAuthAuthorizationCodeMutation(c.config, OpUpdateOne, withOAuthAuthorizationCode(_m))
	return &OAuthAuthorizationCodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OAuthAuthorizationCodeClient) UpdateOneID(id int) *OAuthAuthorizationCodeUpdateOne {
	mutation := newOAuthAuthorizationCodeMutation(c.config, OpUpdateOne, withOAuthAuthorizationCodeID(id))
	return &OAuthAuthorizationCodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OAuthAuthorizationCode.
func (c *OAuthAuthorizationCodeClient) Delete() *OAuthAuthorizationCodeDelete {
	mutation := newOAuthAuthorizationCodeMutation(c.config, OpDelete)
	return &OAuthAuthorizationCodeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OAuthAuthorizationCodeClient) DeleteOne(_m *OAuthAuthorizationCode) *OAuthAuthorizationCodeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OAuthAuthorizationCodeClient) DeleteOneID(id int) *OAuthAuthorizationCodeDeleteOne {
	builder := c.Delete().Where(oauthauthorizationcode.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OAuthAuthorizationCodeDeleteOne{builder}
}

// Query returns a query builder for OAuthAuthorizationCode.
func (c *OAuthAuthorizationCodeClient) Query() *OAuthAuthorizationCodeQuery {
	return &OAuthAuthorizationCodeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOAuthAuthorizationCode},
		inters: c.Interceptors(),
	}
}

// Get returns a OAuthAuthorizationCode entity by its id.
func (c *OAuthAuthorizationCodeClient) Get(ctx context.Context, id int) (*OAuthAuthorizationCode, error) {
	return c.Query().Where(oauthauthorizationcode.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OAuthAuthorizationCodeClient) GetX(ctx context.Context, id int) *OAuthAuthorizationCode {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OAuthAuthorizationCodeClient) Hooks() []Hook {
	return c.hooks.OAuthAuthorizationCode
}

// Interceptors returns the client interceptors.
func (c *OAuthAuthorizationCodeClient) Interceptors() []Interceptor {
	return c.inters.OAuthAuthorizationCode
}

func (c *OAuthAuthorizationCodeClient) mutate(ctx context.Context, m *OAuthAuthorizationCodeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OAuthAuthorizationCodeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OAuthAuthorizationCodeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OAuthAuthorizationCodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OAuthAuthorizationCodeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("_test: unknown OAuthAuthorizationCode mutation op: %q", m.Op())
	}
}

// OAuthClientClient is a client for the OAuthClient schema.
type OAuthClientClient struct {
	config
}

// NewOAuthClientClient returns a client for the OAuthClient from the given config.
func NewOAuthClientClient(c config) *OAuthClientClient {
	return &OAuthClientClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `oauthclient.Hooks(f(g(h())))`.
func (c *OAuthClientClient) Use(hooks ...Hook) {
	c.hooks.OAuthClient = append(c.hooks.OAuthClient, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `oauthclient.Intercept(f(g(h())))`.
func (c *OAuthClientClient) Intercept(interceptors ...Interceptor) {
	c.inters.OAuthClient = append(c.inters.OAuthClient, interceptors...)
}

// Create returns a builder for creating a OAuthClient entity.
func (c *OAuthClientClient) Create() *OAuthClientCreate {
	mutation := newOAuthClientMutation(c.config, OpCreate)
	return &OAuthClientCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OAuthClient entities.
func (c *OAuthClientClient) CreateBulk(builders ...*OAuthClientCreate) *OAuthClientCreateBulk {
	return &OAuthClientCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OAuthClientClient) MapCreateBulk(slice any, setFunc func(*OAuthClientCreate, int)) *OAuthClientCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OAuthClientCreateBulk{err: fmt.Errorf("calling to OAuthClientClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OAuthClientCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OAuthClientCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OAuthClient.
func (c *OAuthClientClient) Update() *OAuthClientUpdate {
	mutation := newOAuthClientMutation(c.config, OpUpdate)
	return &OAuthClientUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OAuthClientClient) UpdateOne(_m *OAuthClient) *OAuthClientUpdateOne {
	mutation := newOAuthClientMutation(c.config, OpUpdateOne, withOAuthClient(_m))
	return &OAuthClientUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OAuthClientClient) UpdateOneID(id int) *OAuthClientUpdateOne {
	mutation := newOAuthClientMutation(c.config, OpUpdateOne, withOAuthClientID(id))
	return &OAuthClientUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OAuthClient.
func (c *OAuthClientClient) Delete() *OAuthClientDelete {
	mutation := newOAuthClientMutation(c.config, OpDelete)
	return &OAuthClientDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OAuthClientClient) DeleteOne(_m *OAuthClient) *OAuthClientDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OAuthClientClient) DeleteOneID(id int) *OAuthClientDeleteOne {
	builder := c.Delete().Where(oauthclient.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OAuthClientDeleteOne{builder}
}

// Query returns a query builder for OAuthClient.
func (c *OAuthClientClient) Query() *OAuthClientQuery {
	return &OAuthClientQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOAuthClient},
		inters: c.Interceptors(),
	}
}

// Get returns a OAuthClient entity by its id.
func (c *OAuthClientClient) Get(ctx context.Context, id int) (*OAuthClient, error) {
	return c.Query().Where(oauthclient.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OAuthClientClient) GetX(ctx context.Context, id int) *OAuthClient {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OAuthClientClient) Hooks() []Hook {
	return c.hooks.OAuthClient
}

// Interceptors returns the client interceptors.
func (c *OAuthClientClient) Interceptors() []Interceptor {
	return c.inters.OAuthClient
}

func (c *OAuthClientClient) mutate(ctx context.Context, m *OAuthClientMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OAuthClientCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OAuthClientUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OAuthClientUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OAuthClientDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("_test: unknown OAuthClient mutation op: %q", m.Op())
	}
}

// OAuthRefreshTokenClient is a client for the OAuthRefreshToken schema.
type OAuthRefreshTokenClient struct {
	config
}

// NewOAuthRefreshTokenClient returns a client for the OAuthRefreshToken from the given config.
func NewOAuthRefreshTokenClient(c config) *OAuthRefreshTokenClient {
	return &OAuthRefreshTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `oauthrefreshtoken.Hooks(f(g(h())))`.
func (c *OAuthRefreshTokenClient) Use(hooks ...Hook) {
	c.hooks.OAuthRefreshToken = append(c.hooks.OAuthRefreshToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `oauthrefreshtoken.Intercept(f(g(h())))`.
func (c *OAuthRefreshTokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.OAuthRefreshToken = append(c.inters.OAuthRefreshToken, interceptors...)
}

// Create returns a builder for creating a OAuthRefreshToken entity.
func (c *OAuthRefreshTokenClient) Create() *OAuthRefreshTokenCreate {
	mutation := newOAuthRefreshTokenMutation(c.config, OpCreate)
	return &OAuthRefreshTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OAuthRefreshToken entities.
func (c *OAuthRefreshTokenClient) CreateBulk(builders ...*OAuthRefreshTokenCreate) *OAuthRefreshTokenCreateBulk {
	return &OAuthRefreshTokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OAuthRefreshTokenClient) MapCreateBulk(slice any, setFunc func(*OAuthRefreshTokenCreate, int)) *OAuthRefreshTokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OAuthRefreshTokenCreateBulk{err: fmt.Errorf("calling to OAuthRefreshTokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OAuthRefreshTokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OAuthRefreshTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OAuthRefreshToken.
func (c *OAuthRefreshTokenClient) Update() *OAuthRefreshTokenUpdate {
	mutation := newOAuthRefreshTokenMutation(c.config, OpUpdate)
	return &OAuthRefreshTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OAuthRefreshTokenClient) UpdateOne(_m *OAuthRefreshToken) *OAuthRefreshTokenUpdateOne {
	mutation := newOAuthRefreshTokenMutation(c.config, OpUpdateOne, withOAuthRefreshToken(_m))
	return &OAuthRefreshTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OAuthRefreshTokenClient) UpdateOneID(id int) *OAuthRefreshTokenUpdateOne {
	mutation := newOAuthRefreshTokenMutation(c.config, OpUpdateOne, withOAuthRefreshTokenID(id))
	return &OAuthRefreshTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OAuthRefreshToken.
func (c *OAuthRefreshTokenClient) Delete() *OAuthRefreshTokenDelete {
	mutation := newOAuthRefreshTokenMutation(c.config, OpDelete)
	return &OAuthRefreshTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OAuthRefreshTokenClient) DeleteOne(_m *OAuthRefreshToken) *OAuthRefreshTokenDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OAuthRefreshTokenClient) DeleteOneID(id int) *OAuthRefreshTokenDeleteOne {
	builder := c.Delete().Where(oauthrefreshtoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OAuthRefreshTokenDeleteOne{builder}
}

// Query returns a query builder for OAuthRefreshToken.
func (c *OAuthRefreshTokenClient) Query() *OAuthRefreshTokenQuery {
	return &OAuthRefreshTokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOAuthRefreshToken},
		inters: c.Interceptors(),
	}
}

// Get returns a OAuthRefreshToken entity by its id.
func (c *OAuthRefreshTokenClient) Get(ctx context.Context, id int) (*OAuthRefreshToken, error) {
	return c.Query().Where(oauthrefreshtoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OAuthRefreshTokenClient) GetX(ctx context.Context, id int) *OAuthRefreshToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OAuthRefreshTokenClient) Hooks() []Hook {
	return c.hooks.OAuthRefreshToken
}

// Interceptors returns the client interceptors.
func (c *OAuthRefreshTokenClient) Interceptors() []Interceptor {
	return c.inters.OAuthRefreshToken
}

func (c *OAuthRefreshTokenClient) mutate(ctx context.Context, m *OAuthRefreshTokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OAuthRefreshTokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OAuthRefreshTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OAuthRefreshTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OAuthRefreshTokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("_test: unknown OAuthRefreshToken mutation op: %q", m.Op())
	}
}

// OAuthSigningKeyClient is a client for the OAuthSigningKey schema.
type OAuthSigningKeyClient struct {
	config
}

// NewOAuthSigningKeyClient returns a client for the OAuthSigningKey from the given config.
func NewOAuthSigningKeyClient(c config) *OAuthSigningKeyClient {
	return &OAuthSigningKeyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `oauthsigningkey.Hooks(f(g(h())))`.
func (c *OAuthSigningKeyClient) Use(hooks ...Hook) {
	c.hooks.OAuthSigningKey = append(c.hooks.OAuthSigningKey, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `oauthsigningkey.Intercept(f(g(h())))`.
func (c *OAuthSigningKeyClient) Intercept(interceptors ...Interceptor) {
	c.inters.OAuthSigningKey = append(c.inters.OAuthSigningKey, interceptors...)
}

// Create returns a builder for creating a OAuthSigningKey entity.
func (c *OAuthSigningKeyClient) Create() *OAuthSigningKeyCreate {
	mutation := newOAuthSigningKeyMutation(c.config, OpCreate)
	return &OAuthSigningKeyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OAuthSigningKey entities.
func (c *OAuthSigningKeyClient) CreateBulk(builders ...*OAuthSigningKeyCreate) *OAuthSigningKeyCreateBulk {
	return &OAuthSigningKeyCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OAuthSigningKeyClient) MapCreateBulk(slice any, setFunc func(*OAuthSigningKeyCreate, int)) *OAuthSigningKeyCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OAuthSigningKeyCreateBulk{err: fmt.Errorf("calling to OAuthSigningKeyClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OAuthSigningKeyCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OAuthSigningKeyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OAuthSigningKey.
func (c *OAuthSigningKeyClient) Update() *OAuthSigningKeyUpdate {
	mutation := newOAuthSigningKeyMutation(c.config, OpUpdate)
	return &OAuthSigningKeyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OAuthSigningKeyClient) UpdateOne(_m *OAuthSigningKey) *OAuthSigningKeyUpdateOne {
	mutation := newOAuthSigningKeyMutation(c.config, OpUpdateOne, withOAuthSigningKey(_m))
	return &OAuthSigningKeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OAuthSigningKeyClient) UpdateOneID(id int) *OAuthSigningKeyUpdateOne {
	mutation := newOAuthSigningKeyMutation(c.config, OpUpdateOne, withOAuthSigningKeyID(id))
	return &OAuthSigningKeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OAuthSigningKey.
func (c *OAuthSigningKeyClient) Delete() *OAuthSigningKeyDelete {
	mutation := newOAuthSigningKeyMutation(c.config, OpDelete)
	return &OAuthSigningKeyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OAuthSigningKeyClient) DeleteOne(_m *OAuthSigningKey) *OAuthSigningKeyDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OAuthSigningKeyClient) DeleteOneID(id int) *OAuthSigningKeyDeleteOne {
	builder := c.Delete().Where(oauthsigningkey.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OAuthSigningKeyDeleteOne{builder}
}

// Query returns a query builder for OAuthSigningKey.
func (c *OAuthSigningKeyClient) Query() *OAuthSigningKeyQuery {
	return &OAuthSigningKeyQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOAuthSigningKey},
		inters: c.Interceptors(),
	}
}

// Get returns a OAuthSigningKey entity by its id.
func (c *OAuthSigningKeyClient) Get(ctx context.Context, id int) (*OAuthSigningKey, error) {
	return c.Query().Where(oauthsigningkey.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OAuthSigningKeyClient) GetX(ctx context.Context, id int) *OAuthSigningKey {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OAuthSigningKeyClient) Hooks() []Hook {
	return c.hooks.OAuthSigningKey
}

// Interceptors returns the client interceptors.
func (c *OAuthSigningKeyClient) Interceptors() []Interceptor {
	return c.inters.OAuthSigningKey
}

func (c *OAuthSigningKeyClient) mutate(ctx context.Context, m *OAuthSigningKeyMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OAuthSigningKeyCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OAuthSigningKeyUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OAuthSigningKeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OAuthSigningKeyDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("_test: unknown OAuthSigningKey mutation op: %q", m.Op())
	}
}

// PersonalAccessTokenClient is a client for the PersonalAccessToken schema.
type PersonalAccessTokenClient struct {
	config
}

// NewPersonalAccessTokenClient returns a client for the PersonalAccessToken from the given config.
func NewPersonalAccessTokenClient(c config) *PersonalAccessTokenClient {
	return &PersonalAccessTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `personalaccesstoken.Hooks(f(g(h())))`.
func (c *PersonalAccessTokenClient) Use(hooks ...Hook) {
	c.hooks.PersonalAccessToken = append(c.hooks.PersonalAccessToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `personalaccesstoken.Intercept(f(g(h())))`.
func (c *PersonalAccessTokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.PersonalAccessToken = append(c.inters.PersonalAccessToken, interceptors...)
}

// Create returns a builder for creating a PersonalAccessToken entity.
func (c *PersonalAccessTokenClient) Create() *PersonalAccessTokenCreate {
	mutation := newPersonalAccessTokenMutation(c.config, OpCreate)
	return &PersonalAccessTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PersonalAccessToken entities.
func (c *PersonalAccessTokenClient) CreateBulk(builders ...*PersonalAccessTokenCreate) *PersonalAccessTokenCreateBulk {
	return &PersonalAccessTokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PersonalAccessTokenClient) MapCreateBulk(slice any, setFunc func(*PersonalAccessTokenCreate, int)) *PersonalAccessTokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PersonalAccessTokenCreateBulk{err: fmt.Errorf("calling to PersonalAccessTokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PersonalAccessTokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PersonalAccessTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PersonalAccessToken.
func (c *PersonalAccessTokenClient) Update() *PersonalAccessTokenUpdate {
	mutation := newPersonalAccessTokenMutation(c.config, OpUpdate)
	return &PersonalAccessTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PersonalAccessTokenClient) UpdateOne(_m *PersonalAccessToken) *PersonalAccessTokenUpdateOne {
	mutation := newPersonalAccessTokenMutation(c.config, OpUpdateOne, withPersonalAccessToken(_m))
	return &PersonalAccessTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PersonalAccessTokenClient) UpdateOneID(id int) *PersonalAccessTokenUpdateOne {
	mutation := newPersonalAccessTokenMutation(c.config, OpUpdateOne, withPersonalAccessTokenID(id))
	return &PersonalAccessTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PersonalAccessToken.
func (c *PersonalAccessTokenClient) Delete() *PersonalAccessTokenDelete {
	mutation := newPersonalAccessTokenMutation(c.config, OpDelete)
	return &PersonalAccessTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PersonalAccessTokenClient) DeleteOne(_m *PersonalAccessToken) *PersonalAccessTokenDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PersonalAccessTokenClient) DeleteOneID(id int) *PersonalAccessTokenDeleteOne {
	builder := c.Delete().Where(personalaccesstoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PersonalAccessTokenDeleteOne{builder}
}

// Query returns a query builder for PersonalAccessToken.
func (c *PersonalAccessTokenClient) Query() *PersonalAccessTokenQuery {
	return &PersonalAccessTokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePersonalAccessToken},
		inters: c.Interceptors(),
	}
}

// Get returns a PersonalAccessToken entity by its id.
func (c *PersonalAccessTokenClient) Get(ctx context.Context, id int) (*PersonalAccessToken, error) {
	return c.Query().Where(personalaccesstoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PersonalAccessTokenClient) GetX(ctx context.Context, id int) *PersonalAccessToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PersonalAccessTokenClient) Hooks() []Hook {
	return c.hooks.PersonalAccessToken
}

// Interceptors returns the client interceptors.
func (c *PersonalAccessTokenClient) Interceptors() []Interceptor {
	return c.inters.PersonalAccessToken
}

func (c *PersonalAccessTokenClient) mutate(ctx context.Context, m *PersonalAccessTokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PersonalAccessTokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PersonalAccessTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PersonalAccessTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PersonalAccessTokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("_test: unknown PersonalAccessToken mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		OAuthAccessToken, OAuthAuthorizationCode, OAuthClient, OAuthRefreshToken,
		OAuthSigningKey, PersonalAccessToken []ent.Hook
	}
	inters struct {
		OAuthAccessToken, OAuthAuthorizationCode, OAuthClient, OAuthRefreshToken,
		OAuthSigningKey, PersonalAccessToken []ent.Interceptor
	}
)
