// Code generated by ent, DO NOT EDIT.

package _test

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/haakco/mcp-kit/entschema/_test/oauthsigningkey"
)

// OAuthSigningKey is the model entity for the OAuthSigningKey schema.
type OAuthSigningKey struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Key ID for JWKS
	Kid string `json:"kid,omitempty"`
	// Signing algorithm
	Algorithm string `json:"algorithm,omitempty"`
	// PEM-encoded RSA private key
	PrivateKeyPem string `json:"-"`
	// PEM-encoded RSA public key
	PublicKeyPem string `json:"public_key_pem,omitempty"`
	// Only active keys sign new tokens
	IsActive bool `json:"is_active,omitempty"`
	// Key expiry for rotation
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// Retired keys stay in JWKS until this time passes
	RetiredAt    *time.Time `json:"retired_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuthSigningKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauthsigningkey.FieldIsActive:
			values[i] = new(sql.NullBool)
		case oauthsigningkey.FieldID:
			values[i] = new(sql.NullInt64)
		case oauthsigningkey.FieldKid, oauthsigningkey.FieldAlgorithm, oauthsigningkey.FieldPrivateKeyPem, oauthsigningkey.FieldPublicKeyPem:
			values[i] = new(sql.NullString)
		case oauthsigningkey.FieldExpiresAt, oauthsigningkey.FieldRetiredAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuthSigningKey fields.
func (_m *OAuthSigningKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauthsigningkey.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case oauthsigningkey.FieldKid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kid", values[i])
			} else if value.Valid {
				_m.Kid = value.String
			}
		case oauthsigningkey.FieldAlgorithm:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field algorithm", values[i])
			} else if value.Valid {
				_m.Algorithm = value.String
			}
		case oauthsigningkey.FieldPrivateKeyPem:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field private_key_pem", values[i])
			} else if value.Valid {
				_m.PrivateKeyPem = value.String
			}
		case oauthsigningkey.FieldPublicKeyPem:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_key_pem", values[i])
			} else if value.Valid {
				_m.PublicKeyPem = value.String
			}
		case oauthsigningkey.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case oauthsigningkey.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case oauthsigningkey.FieldRetiredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field retired_at", values[i])
			} else if value.Valid {
				_m.RetiredAt = new(time.Time)
				*_m.RetiredAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuthSigningKey.
// This includes values selected through modifiers, order, etc.
func (_m *OAuthSigningKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OAuthSigningKey.
// Note that you need to call OAuthSigningKey.Unwrap() before calling this method if this OAuthSigningKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuthSigningKey) Update() *OAuthSigningKeyUpdateOne {
	return NewOAuthSigningKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuthSigningKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuthSigningKey) Unwrap() *OAuthSigningKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("_test: OAuthSigningKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuthSigningKey) String() string {
	var builder strings.Builder
	builder.WriteString("OAuthSigningKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("kid=")
	builder.WriteString(_m.Kid)
	builder.WriteString(", ")
	builder.WriteString("algorithm=")
	builder.WriteString(_m.Algorithm)
	builder.WriteString(", ")
	builder.WriteString("private_key_pem=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("public_key_pem=")
	builder.WriteString(_m.PublicKeyPem)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RetiredAt; v != nil {
		builder.WriteString("retired_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// OAuthSigningKeys is a parsable slice of OAuthSigningKey.
type OAuthSigningKeys []*OAuthSigningKey
