// Code generated by ent, DO NOT EDIT.

package _test

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/haakco/mcp-kit/entschema/_test/oauthauthorizationcode"
	"github.com/haakco/mcp-kit/entschema/_test/predicate"
)

// OAuthAuthorizationCodeUpdate is the builder for updating OAuthAuthorizationCode entities.
type OAuthAuthorizationCodeUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthAuthorizationCodeMutation
}

// Where appends a list predicates to the OAuthAuthorizationCodeUpdate builder.
func (_u *OAuthAuthorizationCodeUpdate) Where(ps ...predicate.OAuthAuthorizationCode) *OAuthAuthorizationCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSessionType sets the "session_type" field.
func (_u *OAuthAuthorizationCodeUpdate) SetSessionType(v string) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetSessionType(v)
	return _u
}

// SetNillableSessionType sets the "session_type" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableSessionType(v *string) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetSessionType(*v)
	}
	return _u
}

// SetSignature sets the "signature" field.
func (_u *OAuthAuthorizationCodeUpdate) SetSignature(v string) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetSignature(v)
	return _u
}

// SetNillableSignature sets the "signature" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableSignature(v *string) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetSignature(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthAuthorizationCodeUpdate) SetClientID(v string) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableClientID(v *string) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthAuthorizationCodeUpdate) SetUserID(v int) *OAuthAuthorizationCodeUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableUserID(v *int) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OAuthAuthorizationCodeUpdate) AddUserID(v int) *OAuthAuthorizationCodeUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *OAuthAuthorizationCodeUpdate) ClearUserID() *OAuthAuthorizationCodeUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *OAuthAuthorizationCodeUpdate) SetRequestID(v string) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableRequestID(v *string) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthAuthorizationCodeUpdate) SetScopes(v string) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// SetNillableScopes sets the "scopes" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableScopes(v *string) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetScopes(*v)
	}
	return _u
}

// SetSessionData sets the "session_data" field.
func (_u *OAuthAuthorizationCodeUpdate) SetSessionData(v map[string]interface{}) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetSessionData(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *OAuthAuthorizationCodeUpdate) SetActive(v bool) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableActive(v *bool) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthAuthorizationCodeUpdate) SetExpiresAt(v time.Time) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableExpiresAt(v *time.Time) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *OAuthAuthorizationCodeUpdate) ClearExpiresAt() *OAuthAuthorizationCodeUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetRequestedAt sets the "requested_at" field.
func (_u *OAuthAuthorizationCodeUpdate) SetRequestedAt(v time.Time) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetRequestedAt(v)
	return _u
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableRequestedAt(v *time.Time) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetRequestedAt(*v)
	}
	return _u
}

// ClearRequestedAt clears the value of the "requested_at" field.
func (_u *OAuthAuthorizationCodeUpdate) ClearRequestedAt() *OAuthAuthorizationCodeUpdate {
	_u.mutation.ClearRequestedAt()
	return _u
}

// Mutation returns the OAuthAuthorizationCodeMutation object of the builder.
func (_u *OAuthAuthorizationCodeUpdate) Mutation() *OAuthAuthorizationCodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthAuthorizationCodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthAuthorizationCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthAuthorizationCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthAuthorizationCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthAuthorizationCodeUpdate) check() error {
	if v, ok := _u.mutation.SessionType(); ok {
		if err := oauthauthorizationcode.SessionTypeValidator(v); err != nil {
			return &ValidationError{Name: "session_type", err: fmt.Errorf(`_test: validator failed for field "OAuthAuthorizationCode.session_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Signature(); ok {
		if err := oauthauthorizationcode.SignatureValidator(v); err != nil {
			return &ValidationError{Name: "signature", err: fmt.Errorf(`_test: validator failed for field "OAuthAuthorizationCode.signature": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthauthorizationcode.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`_test: validator failed for field "OAuthAuthorizationCode.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := oauthauthorizationcode.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`_test: validator failed for field "OAuthAuthorizationCode.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scopes(); ok {
		if err := oauthauthorizationcode.ScopesValidator(v); err != nil {
			return &ValidationError{Name: "scopes", err: fmt.Errorf(`_test: validator failed for field "OAuthAuthorizationCode.scopes": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthAuthorizationCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthauthorizationcode.Table, oauthauthorizationcode.Columns, sqlgraph.NewFieldSpec(oauthauthorizationcode.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionType(); ok {
		_spec.SetField(oauthauthorizationcode.FieldSessionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Signature(); ok {
		_spec.SetField(oauthauthorizationcode.FieldSignature, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(oauthauthorizationcode.FieldUserID, field.TypeInt, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(oauthauthorizationcode.FieldUserID, field.TypeInt)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthauthorizationcode.FieldScopes, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionData(); ok {
		_spec.SetField(oauthauthorizationcode.FieldSessionData, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(oauthauthorizationcode.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthauthorizationcode.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(oauthauthorizationcode.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RequestedAt(); ok {
		_spec.SetField(oauthauthorizationcode.FieldRequestedAt, field.TypeTime, value)
	}
	if _u.mutation.RequestedAtCleared() {
		_spec.ClearField(oauthauthorizationcode.FieldRequestedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthauthorizationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthAuthorizationCodeUpdateOne is the builder for updating a single OAuthAuthorizationCode entity.
type OAuthAuthorizationCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthAuthorizationCodeMutation
}

// SetSessionType sets the "session_type" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetSessionType(v string) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetSessionType(v)
	return _u
}

// SetNillableSessionType sets the "session_type" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableSessionType(v *string) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetSessionType(*v)
	}
	return _u
}

// SetSignature sets the "signature" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetSignature(v string) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetSignature(v)
	return _u
}

// SetNillableSignature sets the "signature" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableSignature(v *string) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetSignature(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetClientID(v string) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableClientID(v *string) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetUserID(v int) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableUserID(v *int) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OAuthAuthorizationCodeUpdateOne) AddUserID(v int) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *OAuthAuthorizationCodeUpdateOne) ClearUserID() *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetRequestID(v string) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableRequestID(v *string) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetScopes(v string) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// SetNillableScopes sets the "scopes" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableScopes(v *string) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetScopes(*v)
	}
	return _u
}

// SetSessionData sets the "session_data" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetSessionData(v map[string]interface{}) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetSessionData(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetActive(v bool) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableActive(v *bool) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetExpiresAt(v time.Time) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableExpiresAt(v *time.Time) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *OAuthAuthorizationCodeUpdateOne) ClearExpiresAt() *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetRequestedAt sets the "requested_at" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetRequestedAt(v time.Time) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetRequestedAt(v)
	return _u
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableRequestedAt(v *time.Time) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetRequestedAt(*v)
	}
	return _u
}

// ClearRequestedAt clears the value of the "requested_at" field.
func (_u *OAuthAuthorizationCodeUpdateOne) ClearRequestedAt() *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.ClearRequestedAt()
	return _u
}

// Mutation returns the OAuthAuthorizationCodeMutation object of the builder.
func (_u *OAuthAuthorizationCodeUpdateOne) Mutation() *OAuthAuthorizationCodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthAuthorizationCodeUpdate builder.
func (_u *OAuthAuthorizationCodeUpdateOne) Where(ps ...predicate.OAuthAuthorizationCode) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthAuthorizationCodeUpdateOne) Select(field string, fields ...string) *OAuthAuthorizationCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthAuthorizationCode entity.
func (_u *OAuthAuthorizationCodeUpdateOne) Save(ctx context.Context) (*OAuthAuthorizationCode, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthAuthorizationCodeUpdateOne) SaveX(ctx context.Context) *OAuthAuthorizationCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthAuthorizationCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthAuthorizationCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthAuthorizationCodeUpdateOne) check() error {
	if v, ok := _u.mutation.SessionType(); ok {
		if err := oauthauthorizationcode.SessionTypeValidator(v); err != nil {
			return &ValidationError{Name: "session_type", err: fmt.Errorf(`_test: validator failed for field "OAuthAuthorizationCode.session_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Signature(); ok {
		if err := oauthauthorizationcode.SignatureValidator(v); err != nil {
			return &ValidationError{Name: "signature", err: fmt.Errorf(`_test: validator failed for field "OAuthAuthorizationCode.signature": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthauthorizationcode.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`_test: validator failed for field "OAuthAuthorizationCode.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := oauthauthorizationcode.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`_test: validator failed for field "OAuthAuthorizationCode.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scopes(); ok {
		if err := oauthauthorizationcode.ScopesValidator(v); err != nil {
			return &ValidationError{Name: "scopes", err: fmt.Errorf(`_test: validator failed for field "OAuthAuthorizationCode.scopes": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthAuthorizationCodeUpdateOne) sqlSave(ctx context.Context) (_node *OAuthAuthorizationCode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthauthorizationcode.Table, oauthauthorizationcode.Columns, sqlgraph.NewFieldSpec(oauthauthorizationcode.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`_test: missing "OAuthAuthorizationCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthauthorizationcode.FieldID)
		for _, f := range fields {
			if !oauthauthorizationcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("_test: invalid field %q for query", f)}
			}
			if f != oauthauthorizationcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionType(); ok {
		_spec.SetField(oauthauthorizationcode.FieldSessionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Signature(); ok {
		_spec.SetField(oauthauthorizationcode.FieldSignature, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(oauthauthorizationcode.FieldUserID, field.TypeInt, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(oauthauthorizationcode.FieldUserID, field.TypeInt)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthauthorizationcode.FieldScopes, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionData(); ok {
		_spec.SetField(oauthauthorizationcode.FieldSessionData, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(oauthauthorizationcode.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthauthorizationcode.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(oauthauthorizationcode.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RequestedAt(); ok {
		_spec.SetField(oauthauthorizationcode.FieldRequestedAt, field.TypeTime, value)
	}
	if _u.mutation.RequestedAtCleared() {
		_spec.ClearField(oauthauthorizationcode.FieldRequestedAt, field.TypeTime)
	}
	_node = &OAuthAuthorizationCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthauthorizationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
