// Code generated by ent, DO NOT EDIT.

package _test

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/haakco/mcp-kit/entschema/_test/oauthsigningkey"
	"github.com/haakco/mcp-kit/entschema/_test/predicate"
)

// OAuthSigningKeyUpdate is the builder for updating OAuthSigningKey entities.
type OAuthSigningKeyUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthSigningKeyMutation
}

// Where appends a list predicates to the OAuthSigningKeyUpdate builder.
func (_u *OAuthSigningKeyUpdate) Where(ps ...predicate.OAuthSigningKey) *OAuthSigningKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKid sets the "kid" field.
func (_u *OAuthSigningKeyUpdate) SetKid(v string) *OAuthSigningKeyUpdate {
	_u.mutation.SetKid(v)
	return _u
}

// SetNillableKid sets the "kid" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdate) SetNillableKid(v *string) *OAuthSigningKeyUpdate {
	if v != nil {
		_u.SetKid(*v)
	}
	return _u
}

// SetAlgorithm sets the "algorithm" field.
func (_u *OAuthSigningKeyUpdate) SetAlgorithm(v string) *OAuthSigningKeyUpdate {
	_u.mutation.SetAlgorithm(v)
	return _u
}

// SetNillableAlgorithm sets the "algorithm" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdate) SetNillableAlgorithm(v *string) *OAuthSigningKeyUpdate {
	if v != nil {
		_u.SetAlgorithm(*v)
	}
	return _u
}

// SetPrivateKeyPem sets the "private_key_pem" field.
func (_u *OAuthSigningKeyUpdate) SetPrivateKeyPem(v string) *OAuthSigningKeyUpdate {
	_u.mutation.SetPrivateKeyPem(v)
	return _u
}

// SetNillablePrivateKeyPem sets the "private_key_pem" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdate) SetNillablePrivateKeyPem(v *string) *OAuthSigningKeyUpdate {
	if v != nil {
		_u.SetPrivateKeyPem(*v)
	}
	return _u
}

// SetPublicKeyPem sets the "public_key_pem" field.
func (_u *OAuthSigningKeyUpdate) SetPublicKeyPem(v string) *OAuthSigningKeyUpdate {
	_u.mutation.SetPublicKeyPem(v)
	return _u
}

// SetNillablePublicKeyPem sets the "public_key_pem" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdate) SetNillablePublicKeyPem(v *string) *OAuthSigningKeyUpdate {
	if v != nil {
		_u.SetPublicKeyPem(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *OAuthSigningKeyUpdate) SetIsActive(v bool) *OAuthSigningKeyUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdate) SetNillableIsActive(v *bool) *OAuthSigningKeyUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthSigningKeyUpdate) SetExpiresAt(v time.Time) *OAuthSigningKeyUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdate) SetNillableExpiresAt(v *time.Time) *OAuthSigningKeyUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *OAuthSigningKeyUpdate) ClearExpiresAt() *OAuthSigningKeyUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetRetiredAt sets the "retired_at" field.
func (_u *OAuthSigningKeyUpdate) SetRetiredAt(v time.Time) *OAuthSigningKeyUpdate {
	_u.mutation.SetRetiredAt(v)
	return _u
}

// SetNillableRetiredAt sets the "retired_at" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdate) SetNillableRetiredAt(v *time.Time) *OAuthSigningKeyUpdate {
	if v != nil {
		_u.SetRetiredAt(*v)
	}
	return _u
}

// ClearRetiredAt clears the value of the "retired_at" field.
func (_u *OAuthSigningKeyUpdate) ClearRetiredAt() *OAuthSigningKeyUpdate {
	_u.mutation.ClearRetiredAt()
	return _u
}

// Mutation returns the OAuthSigningKeyMutation object of the builder.
func (_u *OAuthSigningKeyUpdate) Mutation() *OAuthSigningKeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthSigningKeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthSigningKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthSigningKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthSigningKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthSigningKeyUpdate) check() error {
	if v, ok := _u.mutation.Kid(); ok {
		if err := oauthsigningkey.KidValidator(v); err != nil {
			return &ValidationError{Name: "kid", err: fmt.Errorf(`_test: validator failed for field "OAuthSigningKey.kid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Algorithm(); ok {
		if err := oauthsigningkey.AlgorithmValidator(v); err != nil {
			return &ValidationError{Name: "algorithm", err: fmt.Errorf(`_test: validator failed for field "OAuthSigningKey.algorithm": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthSigningKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthsigningkey.Table, oauthsigningkey.Columns, sqlgraph.NewFieldSpec(oauthsigningkey.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kid(); ok {
		_spec.SetField(oauthsigningkey.FieldKid, field.TypeString, value)
	}
	if value, ok := _u.mutation.Algorithm(); ok {
		_spec.SetField(oauthsigningkey.FieldAlgorithm, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrivateKeyPem(); ok {
		_spec.SetField(oauthsigningkey.FieldPrivateKeyPem, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicKeyPem(); ok {
		_spec.SetField(oauthsigningkey.FieldPublicKeyPem, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(oauthsigningkey.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthsigningkey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(oauthsigningkey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RetiredAt(); ok {
		_spec.SetField(oauthsigningkey.FieldRetiredAt, field.TypeTime, value)
	}
	if _u.mutation.RetiredAtCleared() {
		_spec.ClearField(oauthsigningkey.FieldRetiredAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthsigningkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthSigningKeyUpdateOne is the builder for updating a single OAuthSigningKey entity.
type OAuthSigningKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthSigningKeyMutation
}

// SetKid sets the "kid" field.
func (_u *OAuthSigningKeyUpdateOne) SetKid(v string) *OAuthSigningKeyUpdateOne {
	_u.mutation.SetKid(v)
	return _u
}

// SetNillableKid sets the "kid" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdateOne) SetNillableKid(v *string) *OAuthSigningKeyUpdateOne {
	if v != nil {
		_u.SetKid(*v)
	}
	return _u
}

// SetAlgorithm sets the "algorithm" field.
func (_u *OAuthSigningKeyUpdateOne) SetAlgorithm(v string) *OAuthSigningKeyUpdateOne {
	_u.mutation.SetAlgorithm(v)
	return _u
}

// SetNillableAlgorithm sets the "algorithm" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdateOne) SetNillableAlgorithm(v *string) *OAuthSigningKeyUpdateOne {
	if v != nil {
		_u.SetAlgorithm(*v)
	}
	return _u
}

// SetPrivateKeyPem sets the "private_key_pem" field.
func (_u *OAuthSigningKeyUpdateOne) SetPrivateKeyPem(v string) *OAuthSigningKeyUpdateOne {
	_u.mutation.SetPrivateKeyPem(v)
	return _u
}

// SetNillablePrivateKeyPem sets the "private_key_pem" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdateOne) SetNillablePrivateKeyPem(v *string) *OAuthSigningKeyUpdateOne {
	if v != nil {
		_u.SetPrivateKeyPem(*v)
	}
	return _u
}

// SetPublicKeyPem sets the "public_key_pem" field.
func (_u *OAuthSigningKeyUpdateOne) SetPublicKeyPem(v string) *OAuthSigningKeyUpdateOne {
	_u.mutation.SetPublicKeyPem(v)
	return _u
}

// SetNillablePublicKeyPem sets the "public_key_pem" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdateOne) SetNillablePublicKeyPem(v *string) *OAuthSigningKeyUpdateOne {
	if v != nil {
		_u.SetPublicKeyPem(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *OAuthSigningKeyUpdateOne) SetIsActive(v bool) *OAuthSigningKeyUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdateOne) SetNillableIsActive(v *bool) *OAuthSigningKeyUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthSigningKeyUpdateOne) SetExpiresAt(v time.Time) *OAuthSigningKeyUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdateOne) SetNillableExpiresAt(v *time.Time) *OAuthSigningKeyUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *OAuthSigningKeyUpdateOne) ClearExpiresAt() *OAuthSigningKeyUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetRetiredAt sets the "retired_at" field.
func (_u *OAuthSigningKeyUpdateOne) SetRetiredAt(v time.Time) *OAuthSigningKeyUpdateOne {
	_u.mutation.SetRetiredAt(v)
	return _u
}

// SetNillableRetiredAt sets the "retired_at" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdateOne) SetNillableRetiredAt(v *time.Time) *OAuthSigningKeyUpdateOne {
	if v != nil {
		_u.SetRetiredAt(*v)
	}
	return _u
}

// ClearRetiredAt clears the value of the "retired_at" field.
func (_u *OAuthSigningKeyUpdateOne) ClearRetiredAt() *OAuthSigningKeyUpdateOne {
	_u.mutation.ClearRetiredAt()
	return _u
}

// Mutation returns the OAuthSigningKeyMutation object of the builder.
func (_u *OAuthSigningKeyUpdateOne) Mutation() *OAuthSigningKeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthSigningKeyUpdate builder.
func (_u *OAuthSigningKeyUpdateOne) Where(ps ...predicate.OAuthSigningKey) *OAuthSigningKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthSigningKeyUpdateOne) Select(field string, fields ...string) *OAuthSigningKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthSigningKey entity.
func (_u *OAuthSigningKeyUpdateOne) Save(ctx context.Context) (*OAuthSigningKey, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthSigningKeyUpdateOne) SaveX(ctx context.Context) *OAuthSigningKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthSigningKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthSigningKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthSigningKeyUpdateOne) check() error {
	if v, ok := _u.mutation.Kid(); ok {
		if err := oauthsigningkey.KidValidator(v); err != nil {
			return &ValidationError{Name: "kid", err: fmt.Errorf(`_test: validator failed for field "OAuthSigningKey.kid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Algorithm(); ok {
		if err := oauthsigningkey.AlgorithmValidator(v); err != nil {
			return &ValidationError{Name: "algorithm", err: fmt.Errorf(`_test: validator failed for field "OAuthSigningKey.algorithm": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthSigningKeyUpdateOne) sqlSave(ctx context.Context) (_node *OAuthSigningKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthsigningkey.Table, oauthsigningkey.Columns, sqlgraph.NewFieldSpec(oauthsigningkey.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`_test: missing "OAuthSigningKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthsigningkey.FieldID)
		for _, f := range fields {
			if !oauthsigningkey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("_test: invalid field %q for query", f)}
			}
			if f != oauthsigningkey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kid(); ok {
		_spec.SetField(oauthsigningkey.FieldKid, field.TypeString, value)
	}
	if value, ok := _u.mutation.Algorithm(); ok {
		_spec.SetField(oauthsigningkey.FieldAlgorithm, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrivateKeyPem(); ok {
		_spec.SetField(oauthsigningkey.FieldPrivateKeyPem, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicKeyPem(); ok {
		_spec.SetField(oauthsigningkey.FieldPublicKeyPem, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(oauthsigningkey.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthsigningkey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(oauthsigningkey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RetiredAt(); ok {
		_spec.SetField(oauthsigningkey.FieldRetiredAt, field.TypeTime, value)
	}
	if _u.mutation.RetiredAtCleared() {
		_spec.ClearField(oauthsigningkey.FieldRetiredAt, field.TypeTime)
	}
	_node = &OAuthSigningKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthsigningkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
