// Code generated by ent, DO NOT EDIT.

package _test

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/haakco/mcp-kit/entschema/_test/oauthrefreshtoken"
	"github.com/haakco/mcp-kit/entschema/_test/predicate"
)

// OAuthRefreshTokenUpdate is the builder for updating OAuthRefreshToken entities.
type OAuthRefreshTokenUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthRefreshTokenMutation
}

// Where appends a list predicates to the OAuthRefreshTokenUpdate builder.
func (_u *OAuthRefreshTokenUpdate) Where(ps ...predicate.OAuthRefreshToken) *OAuthRefreshTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSessionType sets the "session_type" field.
func (_u *OAuthRefreshTokenUpdate) SetSessionType(v string) *OAuthRefreshTokenUpdate {
	_u.mutation.SetSessionType(v)
	return _u
}

// SetNillableSessionType sets the "session_type" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdate) SetNillableSessionType(v *string) *OAuthRefreshTokenUpdate {
	if v != nil {
		_u.SetSessionType(*v)
	}
	return _u
}

// SetSignature sets the "signature" field.
func (_u *OAuthRefreshTokenUpdate) SetSignature(v string) *OAuthRefreshTokenUpdate {
	_u.mutation.SetSignature(v)
	return _u
}

// SetNillableSignature sets the "signature" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdate) SetNillableSignature(v *string) *OAuthRefreshTokenUpdate {
	if v != nil {
		_u.SetSignature(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthRefreshTokenUpdate) SetClientID(v string) *OAuthRefreshTokenUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdate) SetNillableClientID(v *string) *OAuthRefreshTokenUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthRefreshTokenUpdate) SetUserID(v int) *OAuthRefreshTokenUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdate) SetNillableUserID(v *int) *OAuthRefreshTokenUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OAuthRefreshTokenUpdate) AddUserID(v int) *OAuthRefreshTokenUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *OAuthRefreshTokenUpdate) ClearUserID() *OAuthRefreshTokenUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *OAuthRefreshTokenUpdate) SetRequestID(v string) *OAuthRefreshTokenUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdate) SetNillableRequestID(v *string) *OAuthRefreshTokenUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthRefreshTokenUpdate) SetScopes(v string) *OAuthRefreshTokenUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// SetNillableScopes sets the "scopes" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdate) SetNillableScopes(v *string) *OAuthRefreshTokenUpdate {
	if v != nil {
		_u.SetScopes(*v)
	}
	return _u
}

// SetSessionData sets the "session_data" field.
func (_u *OAuthRefreshTokenUpdate) SetSessionData(v map[string]interface{}) *OAuthRefreshTokenUpdate {
	_u.mutation.SetSessionData(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *OAuthRefreshTokenUpdate) SetActive(v bool) *OAuthRefreshTokenUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdate) SetNillableActive(v *bool) *OAuthRefreshTokenUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthRefreshTokenUpdate) SetExpiresAt(v time.Time) *OAuthRefreshTokenUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdate) SetNillableExpiresAt(v *time.Time) *OAuthRefreshTokenUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *OAuthRefreshTokenUpdate) ClearExpiresAt() *OAuthRefreshTokenUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetRequestedAt sets the "requested_at" field.
func (_u *OAuthRefreshTokenUpdate) SetRequestedAt(v time.Time) *OAuthRefreshTokenUpdate {
	_u.mutation.SetRequestedAt(v)
	return _u
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdate) SetNillableRequestedAt(v *time.Time) *OAuthRefreshTokenUpdate {
	if v != nil {
		_u.SetRequestedAt(*v)
	}
	return _u
}

// ClearRequestedAt clears the value of the "requested_at" field.
func (_u *OAuthRefreshTokenUpdate) ClearRequestedAt() *OAuthRefreshTokenUpdate {
	_u.mutation.ClearRequestedAt()
	return _u
}

// Mutation returns the OAuthRefreshTokenMutation object of the builder.
func (_u *OAuthRefreshTokenUpdate) Mutation() *OAuthRefreshTokenMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthRefreshTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthRefreshTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthRefreshTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthRefreshTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthRefreshTokenUpdate) check() error {
	if v, ok := _u.mutation.SessionType(); ok {
		if err := oauthrefreshtoken.SessionTypeValidator(v); err != nil {
			return &ValidationError{Name: "session_type", err: fmt.Errorf(`_test: validator failed for field "OAuthRefreshToken.session_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Signature(); ok {
		if err := oauthrefreshtoken.SignatureValidator(v); err != nil {
			return &ValidationError{Name: "signature", err: fmt.Errorf(`_test: validator failed for field "OAuthRefreshToken.signature": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthrefreshtoken.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`_test: validator failed for field "OAuthRefreshToken.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := oauthrefreshtoken.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`_test: validator failed for field "OAuthRefreshToken.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scopes(); ok {
		if err := oauthrefreshtoken.ScopesValidator(v); err != nil {
			return &ValidationError{Name: "scopes", err: fmt.Errorf(`_test: validator failed for field "OAuthRefreshToken.scopes": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthRefreshTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthrefreshtoken.Table, oauthrefreshtoken.Columns, sqlgraph.NewFieldSpec(oauthrefreshtoken.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionType(); ok {
		_spec.SetField(oauthrefreshtoken.FieldSessionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Signature(); ok {
		_spec.SetField(oauthrefreshtoken.FieldSignature, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthrefreshtoken.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthrefreshtoken.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(oauthrefreshtoken.FieldUserID, field.TypeInt, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(oauthrefreshtoken.FieldUserID, field.TypeInt)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(oauthrefreshtoken.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthrefreshtoken.FieldScopes, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionData(); ok {
		_spec.SetField(oauthrefreshtoken.FieldSessionData, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(oauthrefreshtoken.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthrefreshtoken.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(oauthrefreshtoken.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RequestedAt(); ok {
		_spec.SetField(oauthrefreshtoken.FieldRequestedAt, field.TypeTime, value)
	}
	if _u.mutation.RequestedAtCleared() {
		_spec.ClearField(oauthrefreshtoken.FieldRequestedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthrefreshtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthRefreshTokenUpdateOne is the builder for updating a single OAuthRefreshToken entity.
type OAuthRefreshTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthRefreshTokenMutation
}

// SetSessionType sets the "session_type" field.
func (_u *OAuthRefreshTokenUpdateOne) SetSessionType(v string) *OAuthRefreshTokenUpdateOne {
	_u.mutation.SetSessionType(v)
	return _u
}

// SetNillableSessionType sets the "session_type" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdateOne) SetNillableSessionType(v *string) *OAuthRefreshTokenUpdateOne {
	if v != nil {
		_u.SetSessionType(*v)
	}
	return _u
}

// SetSignature sets the "signature" field.
func (_u *OAuthRefreshTokenUpdateOne) SetSignature(v string) *OAuthRefreshTokenUpdateOne {
	_u.mutation.SetSignature(v)
	return _u
}

// SetNillableSignature sets the "signature" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdateOne) SetNillableSignature(v *string) *OAuthRefreshTokenUpdateOne {
	if v != nil {
		_u.SetSignature(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthRefreshTokenUpdateOne) SetClientID(v string) *OAuthRefreshTokenUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdateOne) SetNillableClientID(v *string) *OAuthRefreshTokenUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthRefreshTokenUpdateOne) SetUserID(v int) *OAuthRefreshTokenUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdateOne) SetNillableUserID(v *int) *OAuthRefreshTokenUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OAuthRefreshTokenUpdateOne) AddUserID(v int) *OAuthRefreshTokenUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *OAuthRefreshTokenUpdateOne) ClearUserID() *OAuthRefreshTokenUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *OAuthRefreshTokenUpdateOne) SetRequestID(v string) *OAuthRefreshTokenUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdateOne) SetNillableRequestID(v *string) *OAuthRefreshTokenUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthRefreshTokenUpdateOne) SetScopes(v string) *OAuthRefreshTokenUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// SetNillableScopes sets the "scopes" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdateOne) SetNillableScopes(v *string) *OAuthRefreshTokenUpdateOne {
	if v != nil {
		_u.SetScopes(*v)
	}
	return _u
}

// SetSessionData sets the "session_data" field.
func (_u *OAuthRefreshTokenUpdateOne) SetSessionData(v map[string]interface{}) *OAuthRefreshTokenUpdateOne {
	_u.mutation.SetSessionData(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *OAuthRefreshTokenUpdateOne) SetActive(v bool) *OAuthRefreshTokenUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdateOne) SetNillableActive(v *bool) *OAuthRefreshTokenUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthRefreshTokenUpdateOne) SetExpiresAt(v time.Time) *OAuthRefreshTokenUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdateOne) SetNillableExpiresAt(v *time.Time) *OAuthRefreshTokenUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *OAuthRefreshTokenUpdateOne) ClearExpiresAt() *OAuthRefreshTokenUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetRequestedAt sets the "requested_at" field.
func (_u *OAuthRefreshTokenUpdateOne) SetRequestedAt(v time.Time) *OAuthRefreshTokenUpdateOne {
	_u.mutation.SetRequestedAt(v)
	return _u
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdateOne) SetNillableRequestedAt(v *time.Time) *OAuthRefreshTokenUpdateOne {
	if v != nil {
		_u.SetRequestedAt(*v)
	}
	return _u
}

// ClearRequestedAt clears the value of the "requested_at" field.
func (_u *OAuthRefreshTokenUpdateOne) ClearRequestedAt() *OAuthRefreshTokenUpdateOne {
	_u.mutation.ClearRequestedAt()
	return _u
}

// Mutation returns the OAuthRefreshTokenMutation object of the builder.
func (_u *OAuthRefreshTokenUpdateOne) Mutation() *OAuthRefreshTokenMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthRefreshTokenUpdate builder.
func (_u *OAuthRefreshTokenUpdateOne) Where(ps ...predicate.OAuthRefreshToken) *OAuthRefreshTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthRefreshTokenUpdateOne) Select(field string, fields ...string) *OAuthRefreshTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthRefreshToken entity.
func (_u *OAuthRefreshTokenUpdateOne) Save(ctx context.Context) (*OAuthRefreshToken, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthRefreshTokenUpdateOne) SaveX(ctx context.Context) *OAuthRefreshToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthRefreshTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthRefreshTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthRefreshTokenUpdateOne) check() error {
	if v, ok := _u.mutation.SessionType(); ok {
		if err := oauthrefreshtoken.SessionTypeValidator(v); err != nil {
			return &ValidationError{Name: "session_type", err: fmt.Errorf(`_test: validator failed for field "OAuthRefreshToken.session_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Signature(); ok {
		if err := oauthrefreshtoken.SignatureValidator(v); err != nil {
			return &ValidationError{Name: "signature", err: fmt.Errorf(`_test: validator failed for field "OAuthRefreshToken.signature": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthrefreshtoken.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`_test: validator failed for field "OAuthRefreshToken.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := oauthrefreshtoken.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`_test: validator failed for field "OAuthRefreshToken.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scopes(); ok {
		if err := oauthrefreshtoken.ScopesValidator(v); err != nil {
			return &ValidationError{Name: "scopes", err: fmt.Errorf(`_test: validator failed for field "OAuthRefreshToken.scopes": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthRefreshTokenUpdateOne) sqlSave(ctx context.Context) (_node *OAuthRefreshToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthrefreshtoken.Table, oauthrefreshtoken.Columns, sqlgraph.NewFieldSpec(oauthrefreshtoken.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`_test: missing "OAuthRefreshToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthrefreshtoken.FieldID)
		for _, f := range fields {
			if !oauthrefreshtoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("_test: invalid field %q for query", f)}
			}
			if f != oauthrefreshtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionType(); ok {
		_spec.SetField(oauthrefreshtoken.FieldSessionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Signature(); ok {
		_spec.SetField(oauthrefreshtoken.FieldSignature, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthrefreshtoken.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthrefreshtoken.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(oauthrefreshtoken.FieldUserID, field.TypeInt, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(oauthrefreshtoken.FieldUserID, field.TypeInt)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(oauthrefreshtoken.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthrefreshtoken.FieldScopes, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionData(); ok {
		_spec.SetField(oauthrefreshtoken.FieldSessionData, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(oauthrefreshtoken.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthrefreshtoken.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(oauthrefreshtoken.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RequestedAt(); ok {
		_spec.SetField(oauthrefreshtoken.FieldRequestedAt, field.TypeTime, value)
	}
	if _u.mutation.RequestedAtCleared() {
		_spec.ClearField(oauthrefreshtoken.FieldRequestedAt, field.TypeTime)
	}
	_node = &OAuthRefreshToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthrefreshtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
