// Code generated by ent, DO NOT EDIT.

package _test

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/haakco/mcp-kit/entschema/_test/oauthaccesstoken"
)

// OAuthAccessTokenCreate is the builder for creating a OAuthAccessToken entity.
type OAuthAccessTokenCreate struct {
	config
	mutation *OAuthAccessTokenMutation
	hooks    []Hook
}

// SetSessionType sets the "session_type" field.
func (_c *OAuthAccessTokenCreate) SetSessionType(v string) *OAuthAccessTokenCreate {
	_c.mutation.SetSessionType(v)
	return _c
}

// SetSignature sets the "signature" field.
func (_c *OAuthAccessTokenCreate) SetSignature(v string) *OAuthAccessTokenCreate {
	_c.mutation.SetSignature(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OAuthAccessTokenCreate) SetClientID(v string) *OAuthAccessTokenCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OAuthAccessTokenCreate) SetUserID(v int) *OAuthAccessTokenCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *OAuthAccessTokenCreate) SetNillableUserID(v *int) *OAuthAccessTokenCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *OAuthAccessTokenCreate) SetRequestID(v string) *OAuthAccessTokenCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *OAuthAccessTokenCreate) SetNillableRequestID(v *string) *OAuthAccessTokenCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *OAuthAccessTokenCreate) SetScopes(v string) *OAuthAccessTokenCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetNillableScopes sets the "scopes" field if the given value is not nil.
func (_c *OAuthAccessTokenCreate) SetNillableScopes(v *string) *OAuthAccessTokenCreate {
	if v != nil {
		_c.SetScopes(*v)
	}
	return _c
}

// SetSessionData sets the "session_data" field.
func (_c *OAuthAccessTokenCreate) SetSessionData(v map[string]interface{}) *OAuthAccessTokenCreate {
	_c.mutation.SetSessionData(v)
	return _c
}

// SetActive sets the "active" field.
func (_c *OAuthAccessTokenCreate) SetActive(v bool) *OAuthAccessTokenCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *OAuthAccessTokenCreate) SetNillableActive(v *bool) *OAuthAccessTokenCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OAuthAccessTokenCreate) SetExpiresAt(v time.Time) *OAuthAccessTokenCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *OAuthAccessTokenCreate) SetNillableExpiresAt(v *time.Time) *OAuthAccessTokenCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetRequestedAt sets the "requested_at" field.
func (_c *OAuthAccessTokenCreate) SetRequestedAt(v time.Time) *OAuthAccessTokenCreate {
	_c.mutation.SetRequestedAt(v)
	return _c
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_c *OAuthAccessTokenCreate) SetNillableRequestedAt(v *time.Time) *OAuthAccessTokenCreate {
	if v != nil {
		_c.SetRequestedAt(*v)
	}
	return _c
}

// Mutation returns the OAuthAccessTokenMutation object of the builder.
func (_c *OAuthAccessTokenCreate) Mutation() *OAuthAccessTokenMutation {
	return _c.mutation
}

// Save creates the OAuthAccessToken in the database.
func (_c *OAuthAccessTokenCreate) Save(ctx context.Context) (*OAuthAccessToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthAccessTokenCreate) SaveX(ctx context.Context) *OAuthAccessToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthAccessTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthAccessTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthAccessTokenCreate) defaults() {
	if _, ok := _c.mutation.RequestID(); !ok {
		v := oauthaccesstoken.DefaultRequestID
		_c.mutation.SetRequestID(v)
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		v := oauthaccesstoken.DefaultScopes
		_c.mutation.SetScopes(v)
	}
	if _, ok := _c.mutation.SessionData(); !ok {
		v := oauthaccesstoken.DefaultSessionData
		_c.mutation.SetSessionData(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := oauthaccesstoken.DefaultActive
		_c.mutation.SetActive(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthAccessTokenCreate) check() error {
	if _, ok := _c.mutation.SessionType(); !ok {
		return &ValidationError{Name: "session_type", err: errors.New(`_test: missing required field "OAuthAccessToken.session_type"`)}
	}
	if v, ok := _c.mutation.SessionType(); ok {
		if err := oauthaccesstoken.SessionTypeValidator(v); err != nil {
			return &ValidationError{Name: "session_type", err: fmt.Errorf(`_test: validator failed for field "OAuthAccessToken.session_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Signature(); !ok {
		return &ValidationError{Name: "signature", err: errors.New(`_test: missing required field "OAuthAccessToken.signature"`)}
	}
	if v, ok := _c.mutation.Signature(); ok {
		if err := oauthaccesstoken.SignatureValidator(v); err != nil {
			return &ValidationError{Name: "signature", err: fmt.Errorf(`_test: validator failed for field "OAuthAccessToken.signature": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`_test: missing required field "OAuthAccessToken.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := oauthaccesstoken.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`_test: validator failed for field "OAuthAccessToken.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`_test: missing required field "OAuthAccessToken.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := oauthaccesstoken.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`_test: validator failed for field "OAuthAccessToken.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`_test: missing required field "OAuthAccessToken.scopes"`)}
	}
	if v, ok := _c.mutation.Scopes(); ok {
		if err := oauthaccesstoken.ScopesValidator(v); err != nil {
			return &ValidationError{Name: "scopes", err: fmt.Errorf(`_test: validator failed for field "OAuthAccessToken.scopes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SessionData(); !ok {
		return &ValidationError{Name: "session_data", err: errors.New(`_test: missing required field "OAuthAccessToken.session_data"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`_test: missing required field "OAuthAccessToken.active"`)}
	}
	return nil
}

func (_c *OAuthAccessTokenCreate) sqlSave(ctx context.Context) (*OAuthAccessToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthAccessTokenCreate) createSpec() (*OAuthAccessToken, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthAccessToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthaccesstoken.Table, sqlgraph.NewFieldSpec(oauthaccesstoken.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.SessionType(); ok {
		_spec.SetField(oauthaccesstoken.FieldSessionType, field.TypeString, value)
		_node.SessionType = value
	}
	if value, ok := _c.mutation.Signature(); ok {
		_spec.SetField(oauthaccesstoken.FieldSignature, field.TypeString, value)
		_node.Signature = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauthaccesstoken.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(oauthaccesstoken.FieldUserID, field.TypeInt, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(oauthaccesstoken.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(oauthaccesstoken.FieldScopes, field.TypeString, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.SessionData(); ok {
		_spec.SetField(oauthaccesstoken.FieldSessionData, field.TypeJSON, value)
		_node.SessionData = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(oauthaccesstoken.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthaccesstoken.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.RequestedAt(); ok {
		_spec.SetField(oauthaccesstoken.FieldRequestedAt, field.TypeTime, value)
		_node.RequestedAt = &value
	}
	return _node, _spec
}

// OAuthAccessTokenCreateBulk is the builder for creating many OAuthAccessToken entities in bulk.
type OAuthAccessTokenCreateBulk struct {
	config
	err      error
	builders []*OAuthAccessTokenCreate
}

// Save creates the OAuthAccessToken entities in the database.
func (_c *OAuthAccessTokenCreateBulk) Save(ctx context.Context) ([]*OAuthAccessToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthAccessToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthAccessTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthAccessTokenCreateBulk) SaveX(ctx context.Context) []*OAuthAccessToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthAccessTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthAccessTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
