// Code generated by ent, DO NOT EDIT.

package _test

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/haakco/mcp-kit/entschema/_test/oauthaccesstoken"
	"github.com/haakco/mcp-kit/entschema/_test/predicate"
)

// OAuthAccessTokenUpdate is the builder for updating OAuthAccessToken entities.
type OAuthAccessTokenUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthAccessTokenMutation
}

// Where appends a list predicates to the OAuthAccessTokenUpdate builder.
func (_u *OAuthAccessTokenUpdate) Where(ps ...predicate.OAuthAccessToken) *OAuthAccessTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSessionType sets the "session_type" field.
func (_u *OAuthAccessTokenUpdate) SetSessionType(v string) *OAuthAccessTokenUpdate {
	_u.mutation.SetSessionType(v)
	return _u
}

// SetNillableSessionType sets the "session_type" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdate) SetNillableSessionType(v *string) *OAuthAccessTokenUpdate {
	if v != nil {
		_u.SetSessionType(*v)
	}
	return _u
}

// SetSignature sets the "signature" field.
func (_u *OAuthAccessTokenUpdate) SetSignature(v string) *OAuthAccessTokenUpdate {
	_u.mutation.SetSignature(v)
	return _u
}

// SetNillableSignature sets the "signature" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdate) SetNillableSignature(v *string) *OAuthAccessTokenUpdate {
	if v != nil {
		_u.SetSignature(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthAccessTokenUpdate) SetClientID(v string) *OAuthAccessTokenUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdate) SetNillableClientID(v *string) *OAuthAccessTokenUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthAccessTokenUpdate) SetUserID(v int) *OAuthAccessTokenUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdate) SetNillableUserID(v *int) *OAuthAccessTokenUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OAuthAccessTokenUpdate) AddUserID(v int) *OAuthAccessTokenUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *OAuthAccessTokenUpdate) ClearUserID() *OAuthAccessTokenUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *OAuthAccessTokenUpdate) SetRequestID(v string) *OAuthAccessTokenUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdate) SetNillableRequestID(v *string) *OAuthAccessTokenUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthAccessTokenUpdate) SetScopes(v string) *OAuthAccessTokenUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// SetNillableScopes sets the "scopes" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdate) SetNillableScopes(v *string) *OAuthAccessTokenUpdate {
	if v != nil {
		_u.SetScopes(*v)
	}
	return _u
}

// SetSessionData sets the "session_data" field.
func (_u *OAuthAccessTokenUpdate) SetSessionData(v map[string]interface{}) *OAuthAccessTokenUpdate {
	_u.mutation.SetSessionData(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *OAuthAccessTokenUpdate) SetActive(v bool) *OAuthAccessTokenUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdate) SetNillableActive(v *bool) *OAuthAccessTokenUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthAccessTokenUpdate) SetExpiresAt(v time.Time) *OAuthAccessTokenUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdate) SetNillableExpiresAt(v *time.Time) *OAuthAccessTokenUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *OAuthAccessTokenUpdate) ClearExpiresAt() *OAuthAccessTokenUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetRequestedAt sets the "requested_at" field.
func (_u *OAuthAccessTokenUpdate) SetRequestedAt(v time.Time) *OAuthAccessTokenUpdate {
	_u.mutation.SetRequestedAt(v)
	return _u
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdate) SetNillableRequestedAt(v *time.Time) *OAuthAccessTokenUpdate {
	if v != nil {
		_u.SetRequestedAt(*v)
	}
	return _u
}

// ClearRequestedAt clears the value of the "requested_at" field.
func (_u *OAuthAccessTokenUpdate) ClearRequestedAt() *OAuthAccessTokenUpdate {
	_u.mutation.ClearRequestedAt()
	return _u
}

// Mutation returns the OAuthAccessTokenMutation object of the builder.
func (_u *OAuthAccessTokenUpdate) Mutation() *OAuthAccessTokenMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthAccessTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthAccessTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthAccessTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthAccessTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthAccessTokenUpdate) check() error {
	if v, ok := _u.mutation.SessionType(); ok {
		if err := oauthaccesstoken.SessionTypeValidator(v); err != nil {
			return &ValidationError{Name: "session_type", err: fmt.Errorf(`_test: validator failed for field "OAuthAccessToken.session_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Signature(); ok {
		if err := oauthaccesstoken.SignatureValidator(v); err != nil {
			return &ValidationError{Name: "signature", err: fmt.Errorf(`_test: validator failed for field "OAuthAccessToken.signature": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthaccesstoken.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`_test: validator failed for field "OAuthAccessToken.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := oauthaccesstoken.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`_test: validator failed for field "OAuthAccessToken.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scopes(); ok {
		if err := oauthaccesstoken.ScopesValidator(v); err != nil {
			return &ValidationError{Name: "scopes", err: fmt.Errorf(`_test: validator failed for field "OAuthAccessToken.scopes": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthAccessTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthaccesstoken.Table, oauthaccesstoken.Columns, sqlgraph.NewFieldSpec(oauthaccesstoken.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionType(); ok {
		_spec.SetField(oauthaccesstoken.FieldSessionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Signature(); ok {
		_spec.SetField(oauthaccesstoken.FieldSignature, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthaccesstoken.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthaccesstoken.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(oauthaccesstoken.FieldUserID, field.TypeInt, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(oauthaccesstoken.FieldUserID, field.TypeInt)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(oauthaccesstoken.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthaccesstoken.FieldScopes, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionData(); ok {
		_spec.SetField(oauthaccesstoken.FieldSessionData, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(oauthaccesstoken.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthaccesstoken.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(oauthaccesstoken.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RequestedAt(); ok {
		_spec.SetField(oauthaccesstoken.FieldRequestedAt, field.TypeTime, value)
	}
	if _u.mutation.RequestedAtCleared() {
		_spec.ClearField(oauthaccesstoken.FieldRequestedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthaccesstoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthAccessTokenUpdateOne is the builder for updating a single OAuthAccessToken entity.
type OAuthAccessTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthAccessTokenMutation
}

// SetSessionType sets the "session_type" field.
func (_u *OAuthAccessTokenUpdateOne) SetSessionType(v string) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetSessionType(v)
	return _u
}

// SetNillableSessionType sets the "session_type" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdateOne) SetNillableSessionType(v *string) *OAuthAccessTokenUpdateOne {
	if v != nil {
		_u.SetSessionType(*v)
	}
	return _u
}

// SetSignature sets the "signature" field.
func (_u *OAuthAccessTokenUpdateOne) SetSignature(v string) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetSignature(v)
	return _u
}

// SetNillableSignature sets the "signature" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdateOne) SetNillableSignature(v *string) *OAuthAccessTokenUpdateOne {
	if v != nil {
		_u.SetSignature(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthAccessTokenUpdateOne) SetClientID(v string) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdateOne) SetNillableClientID(v *string) *OAuthAccessTokenUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthAccessTokenUpdateOne) SetUserID(v int) *OAuthAccessTokenUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdateOne) SetNillableUserID(v *int) *OAuthAccessTokenUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OAuthAccessTokenUpdateOne) AddUserID(v int) *OAuthAccessTokenUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *OAuthAccessTokenUpdateOne) ClearUserID() *OAuthAccessTokenUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *OAuthAccessTokenUpdateOne) SetRequestID(v string) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdateOne) SetNillableRequestID(v *string) *OAuthAccessTokenUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthAccessTokenUpdateOne) SetScopes(v string) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// SetNillableScopes sets the "scopes" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdateOne) SetNillableScopes(v *string) *OAuthAccessTokenUpdateOne {
	if v != nil {
		_u.SetScopes(*v)
	}
	return _u
}

// SetSessionData sets the "session_data" field.
func (_u *OAuthAccessTokenUpdateOne) SetSessionData(v map[string]interface{}) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetSessionData(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *OAuthAccessTokenUpdateOne) SetActive(v bool) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdateOne) SetNillableActive(v *bool) *OAuthAccessTokenUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthAccessTokenUpdateOne) SetExpiresAt(v time.Time) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdateOne) SetNillableExpiresAt(v *time.Time) *OAuthAccessTokenUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *OAuthAccessTokenUpdateOne) ClearExpiresAt() *OAuthAccessTokenUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetRequestedAt sets the "requested_at" field.
func (_u *OAuthAccessTokenUpdateOne) SetRequestedAt(v time.Time) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetRequestedAt(v)
	return _u
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdateOne) SetNillableRequestedAt(v *time.Time) *OAuthAccessTokenUpdateOne {
	if v != nil {
		_u.SetRequestedAt(*v)
	}
	return _u
}

// ClearRequestedAt clears the value of the "requested_at" field.
func (_u *OAuthAccessTokenUpdateOne) ClearRequestedAt() *OAuthAccessTokenUpdateOne {
	_u.mutation.ClearRequestedAt()
	return _u
}

// Mutation returns the OAuthAccessTokenMutation object of the builder.
func (_u *OAuthAccessTokenUpdateOne) Mutation() *OAuthAccessTokenMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthAccessTokenUpdate builder.
func (_u *OAuthAccessTokenUpdateOne) Where(ps ...predicate.OAuthAccessToken) *OAuthAccessTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthAccessTokenUpdateOne) Select(field string, fields ...string) *OAuthAccessTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthAccessToken entity.
func (_u *OAuthAccessTokenUpdateOne) Save(ctx context.Context) (*OAuthAccessToken, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthAccessTokenUpdateOne) SaveX(ctx context.Context) *OAuthAccessToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthAccessTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthAccessTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthAccessTokenUpdateOne) check() error {
	if v, ok := _u.mutation.SessionType(); ok {
		if err := oauthaccesstoken.SessionTypeValidator(v); err != nil {
			return &ValidationError{Name: "session_type", err: fmt.Errorf(`_test: validator failed for field "OAuthAccessToken.session_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Signature(); ok {
		if err := oauthaccesstoken.SignatureValidator(v); err != nil {
			return &ValidationError{Name: "signature", err: fmt.Errorf(`_test: validator failed for field "OAuthAccessToken.signature": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthaccesstoken.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`_test: validator failed for field "OAuthAccessToken.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := oauthaccesstoken.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`_test: validator failed for field "OAuthAccessToken.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scopes(); ok {
		if err := oauthaccesstoken.ScopesValidator(v); err != nil {
			return &ValidationError{Name: "scopes", err: fmt.Errorf(`_test: validator failed for field "OAuthAccessToken.scopes": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthAccessTokenUpdateOne) sqlSave(ctx context.Context) (_node *OAuthAccessToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthaccesstoken.Table, oauthaccesstoken.Columns, sqlgraph.NewFieldSpec(oauthaccesstoken.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`_test: missing "OAuthAccessToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthaccesstoken.FieldID)
		for _, f := range fields {
			if !oauthaccesstoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("_test: invalid field %q for query", f)}
			}
			if f != oauthaccesstoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionType(); ok {
		_spec.SetField(oauthaccesstoken.FieldSessionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Signature(); ok {
		_spec.SetField(oauthaccesstoken.FieldSignature, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthaccesstoken.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthaccesstoken.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(oauthaccesstoken.FieldUserID, field.TypeInt, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(oauthaccesstoken.FieldUserID, field.TypeInt)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(oauthaccesstoken.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthaccesstoken.FieldScopes, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionData(); ok {
		_spec.SetField(oauthaccesstoken.FieldSessionData, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(oauthaccesstoken.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthaccesstoken.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(oauthaccesstoken.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RequestedAt(); ok {
		_spec.SetField(oauthaccesstoken.FieldRequestedAt, field.TypeTime, value)
	}
	if _u.mutation.RequestedAtCleared() {
		_spec.ClearField(oauthaccesstoken.FieldRequestedAt, field.TypeTime)
	}
	_node = &OAuthAccessToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthaccesstoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
