// Code generated by ent, DO NOT EDIT.

package _test

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/haakco/mcp-kit/entschema/_test/oauthsigningkey"
)

// OAuthSigningKeyCreate is the builder for creating a OAuthSigningKey entity.
type OAuthSigningKeyCreate struct {
	config
	mutation *OAuthSigningKeyMutation
	hooks    []Hook
}

// SetKid sets the "kid" field.
func (_c *OAuthSigningKeyCreate) SetKid(v string) *OAuthSigningKeyCreate {
	_c.mutation.SetKid(v)
	return _c
}

// SetAlgorithm sets the "algorithm" field.
func (_c *OAuthSigningKeyCreate) SetAlgorithm(v string) *OAuthSigningKeyCreate {
	_c.mutation.SetAlgorithm(v)
	return _c
}

// SetNillableAlgorithm sets the "algorithm" field if the given value is not nil.
func (_c *OAuthSigningKeyCreate) SetNillableAlgorithm(v *string) *OAuthSigningKeyCreate {
	if v != nil {
		_c.SetAlgorithm(*v)
	}
	return _c
}

// SetPrivateKeyPem sets the "private_key_pem" field.
func (_c *OAuthSigningKeyCreate) SetPrivateKeyPem(v string) *OAuthSigningKeyCreate {
	_c.mutation.SetPrivateKeyPem(v)
	return _c
}

// SetPublicKeyPem sets the "public_key_pem" field.
func (_c *OAuthSigningKeyCreate) SetPublicKeyPem(v string) *OAuthSigningKeyCreate {
	_c.mutation.SetPublicKeyPem(v)
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *OAuthSigningKeyCreate) SetIsActive(v bool) *OAuthSigningKeyCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *OAuthSigningKeyCreate) SetNillableIsActive(v *bool) *OAuthSigningKeyCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OAuthSigningKeyCreate) SetExpiresAt(v time.Time) *OAuthSigningKeyCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *OAuthSigningKeyCreate) SetNillableExpiresAt(v *time.Time) *OAuthSigningKeyCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetRetiredAt sets the "retired_at" field.
func (_c *OAuthSigningKeyCreate) SetRetiredAt(v time.Time) *OAuthSigningKeyCreate {
	_c.mutation.SetRetiredAt(v)
	return _c
}

// SetNillableRetiredAt sets the "retired_at" field if the given value is not nil.
func (_c *OAuthSigningKeyCreate) SetNillableRetiredAt(v *time.Time) *OAuthSigningKeyCreate {
	if v != nil {
		_c.SetRetiredAt(*v)
	}
	return _c
}

// Mutation returns the OAuthSigningKeyMutation object of the builder.
func (_c *OAuthSigningKeyCreate) Mutation() *OAuthSigningKeyMutation {
	return _c.mutation
}

// Save creates the OAuthSigningKey in the database.
func (_c *OAuthSigningKeyCreate) Save(ctx context.Context) (*OAuthSigningKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthSigningKeyCreate) SaveX(ctx context.Context) *OAuthSigningKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthSigningKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthSigningKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthSigningKeyCreate) defaults() {
	if _, ok := _c.mutation.Algorithm(); !ok {
		v := oauthsigningkey.DefaultAlgorithm
		_c.mutation.SetAlgorithm(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := oauthsigningkey.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthSigningKeyCreate) check() error {
	if _, ok := _c.mutation.Kid(); !ok {
		return &ValidationError{Name: "kid", err: errors.New(`_test: missing required field "OAuthSigningKey.kid"`)}
	}
	if v, ok := _c.mutation.Kid(); ok {
		if err := oauthsigningkey.KidValidator(v); err != nil {
			return &ValidationError{Name: "kid", err: fmt.Errorf(`_test: validator failed for field "OAuthSigningKey.kid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Algorithm(); !ok {
		return &ValidationError{Name: "algorithm", err: errors.New(`_test: missing required field "OAuthSigningKey.algorithm"`)}
	}
	if v, ok := _c.mutation.Algorithm(); ok {
		if err := oauthsigningkey.AlgorithmValidator(v); err != nil {
			return &ValidationError{Name: "algorithm", err: fmt.Errorf(`_test: validator failed for field "OAuthSigningKey.algorithm": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PrivateKeyPem(); !ok {
		return &ValidationError{Name: "private_key_pem", err: errors.New(`_test: missing required field "OAuthSigningKey.private_key_pem"`)}
	}
	if _, ok := _c.mutation.PublicKeyPem(); !ok {
		return &ValidationError{Name: "public_key_pem", err: errors.New(`_test: missing required field "OAuthSigningKey.public_key_pem"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`_test: missing required field "OAuthSigningKey.is_active"`)}
	}
	return nil
}

func (_c *OAuthSigningKeyCreate) sqlSave(ctx context.Context) (*OAuthSigningKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthSigningKeyCreate) createSpec() (*OAuthSigningKey, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthSigningKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthsigningkey.Table, sqlgraph.NewFieldSpec(oauthsigningkey.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Kid(); ok {
		_spec.SetField(oauthsigningkey.FieldKid, field.TypeString, value)
		_node.Kid = value
	}
	if value, ok := _c.mutation.Algorithm(); ok {
		_spec.SetField(oauthsigningkey.FieldAlgorithm, field.TypeString, value)
		_node.Algorithm = value
	}
	if value, ok := _c.mutation.PrivateKeyPem(); ok {
		_spec.SetField(oauthsigningkey.FieldPrivateKeyPem, field.TypeString, value)
		_node.PrivateKeyPem = value
	}
	if value, ok := _c.mutation.PublicKeyPem(); ok {
		_spec.SetField(oauthsigningkey.FieldPublicKeyPem, field.TypeString, value)
		_node.PublicKeyPem = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(oauthsigningkey.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthsigningkey.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.RetiredAt(); ok {
		_spec.SetField(oauthsigningkey.FieldRetiredAt, field.TypeTime, value)
		_node.RetiredAt = &value
	}
	return _node, _spec
}

// OAuthSigningKeyCreateBulk is the builder for creating many OAuthSigningKey entities in bulk.
type OAuthSigningKeyCreateBulk struct {
	config
	err      error
	builders []*OAuthSigningKeyCreate
}

// Save creates the OAuthSigningKey entities in the database.
func (_c *OAuthSigningKeyCreateBulk) Save(ctx context.Context) ([]*OAuthSigningKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthSigningKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthSigningKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthSigningKeyCreateBulk) SaveX(ctx context.Context) []*OAuthSigningKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthSigningKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthSigningKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
