// Code generated by ent, DO NOT EDIT.

package _test

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/haakco/mcp-kit/entschema/_test/oauthclient"
)

// OAuthClientCreate is the builder for creating a OAuthClient entity.
type OAuthClientCreate struct {
	config
	mutation *OAuthClientMutation
	hooks    []Hook
}

// SetClientID sets the "client_id" field.
func (_c *OAuthClientCreate) SetClientID(v string) *OAuthClientCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (_c *OAuthClientCreate) SetClientSecretHash(v string) *OAuthClientCreate {
	_c.mutation.SetClientSecretHash(v)
	return _c
}

// SetNillableClientSecretHash sets the "client_secret_hash" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableClientSecretHash(v *string) *OAuthClientCreate {
	if v != nil {
		_c.SetClientSecretHash(*v)
	}
	return _c
}

// SetRedirectUris sets the "redirect_uris" field.
func (_c *OAuthClientCreate) SetRedirectUris(v []string) *OAuthClientCreate {
	_c.mutation.SetRedirectUris(v)
	return _c
}

// SetGrantTypes sets the "grant_types" field.
func (_c *OAuthClientCreate) SetGrantTypes(v []string) *OAuthClientCreate {
	_c.mutation.SetGrantTypes(v)
	return _c
}

// SetResponseTypes sets the "response_types" field.
func (_c *OAuthClientCreate) SetResponseTypes(v []string) *OAuthClientCreate {
	_c.mutation.SetResponseTypes(v)
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *OAuthClientCreate) SetScopes(v string) *OAuthClientCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetNillableScopes sets the "scopes" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableScopes(v *string) *OAuthClientCreate {
	if v != nil {
		_c.SetScopes(*v)
	}
	return _c
}

// SetIsPublic sets the "is_public" field.
func (_c *OAuthClientCreate) SetIsPublic(v bool) *OAuthClientCreate {
	_c.mutation.SetIsPublic(v)
	return _c
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableIsPublic(v *bool) *OAuthClientCreate {
	if v != nil {
		_c.SetIsPublic(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *OAuthClientCreate) SetName(v string) *OAuthClientCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *OAuthClientCreate) SetWorkspaceID(v int) *OAuthClientCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableWorkspaceID(v *int) *OAuthClientCreate {
	if v != nil {
		_c.SetWorkspaceID(*v)
	}
	return _c
}

// Mutation returns the OAuthClientMutation object of the builder.
func (_c *OAuthClientCreate) Mutation() *OAuthClientMutation {
	return _c.mutation
}

// Save creates the OAuthClient in the database.
func (_c *OAuthClientCreate) Save(ctx context.Context) (*OAuthClient, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthClientCreate) SaveX(ctx context.Context) *OAuthClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthClientCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthClientCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthClientCreate) defaults() {
	if _, ok := _c.mutation.ClientSecretHash(); !ok {
		v := oauthclient.DefaultClientSecretHash
		_c.mutation.SetClientSecretHash(v)
	}
	if _, ok := _c.mutation.RedirectUris(); !ok {
		v := oauthclient.DefaultRedirectUris
		_c.mutation.SetRedirectUris(v)
	}
	if _, ok := _c.mutation.GrantTypes(); !ok {
		v := oauthclient.DefaultGrantTypes
		_c.mutation.SetGrantTypes(v)
	}
	if _, ok := _c.mutation.ResponseTypes(); !ok {
		v := oauthclient.DefaultResponseTypes
		_c.mutation.SetResponseTypes(v)
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		v := oauthclient.DefaultScopes
		_c.mutation.SetScopes(v)
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		v := oauthclient.DefaultIsPublic
		_c.mutation.SetIsPublic(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthClientCreate) check() error {
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`_test: missing required field "OAuthClient.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := oauthclient.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`_test: validator failed for field "OAuthClient.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientSecretHash(); !ok {
		return &ValidationError{Name: "client_secret_hash", err: errors.New(`_test: missing required field "OAuthClient.client_secret_hash"`)}
	}
	if _, ok := _c.mutation.RedirectUris(); !ok {
		return &ValidationError{Name: "redirect_uris", err: errors.New(`_test: missing required field "OAuthClient.redirect_uris"`)}
	}
	if _, ok := _c.mutation.GrantTypes(); !ok {
		return &ValidationError{Name: "grant_types", err: errors.New(`_test: missing required field "OAuthClient.grant_types"`)}
	}
	if _, ok := _c.mutation.ResponseTypes(); !ok {
		return &ValidationError{Name: "response_types", err: errors.New(`_test: missing required field "OAuthClient.response_types"`)}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`_test: missing required field "OAuthClient.scopes"`)}
	}
	if v, ok := _c.mutation.Scopes(); ok {
		if err := oauthclient.ScopesValidator(v); err != nil {
			return &ValidationError{Name: "scopes", err: fmt.Errorf(`_test: validator failed for field "OAuthClient.scopes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		return &ValidationError{Name: "is_public", err: errors.New(`_test: missing required field "OAuthClient.is_public"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`_test: missing required field "OAuthClient.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := oauthclient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`_test: validator failed for field "OAuthClient.name": %w`, err)}
		}
	}
	return nil
}

func (_c *OAuthClientCreate) sqlSave(ctx context.Context) (*OAuthClient, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthClientCreate) createSpec() (*OAuthClient, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthClient{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthclient.Table, sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauthclient.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.ClientSecretHash(); ok {
		_spec.SetField(oauthclient.FieldClientSecretHash, field.TypeString, value)
		_node.ClientSecretHash = value
	}
	if value, ok := _c.mutation.RedirectUris(); ok {
		_spec.SetField(oauthclient.FieldRedirectUris, field.TypeJSON, value)
		_node.RedirectUris = value
	}
	if value, ok := _c.mutation.GrantTypes(); ok {
		_spec.SetField(oauthclient.FieldGrantTypes, field.TypeJSON, value)
		_node.GrantTypes = value
	}
	if value, ok := _c.mutation.ResponseTypes(); ok {
		_spec.SetField(oauthclient.FieldResponseTypes, field.TypeJSON, value)
		_node.ResponseTypes = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(oauthclient.FieldScopes, field.TypeString, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.IsPublic(); ok {
		_spec.SetField(oauthclient.FieldIsPublic, field.TypeBool, value)
		_node.IsPublic = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(oauthclient.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.WorkspaceID(); ok {
		_spec.SetField(oauthclient.FieldWorkspaceID, field.TypeInt, value)
		_node.WorkspaceID = &value
	}
	return _node, _spec
}

// OAuthClientCreateBulk is the builder for creating many OAuthClient entities in bulk.
type OAuthClientCreateBulk struct {
	config
	err      error
	builders []*OAuthClientCreate
}

// Save creates the OAuthClient entities in the database.
func (_c *OAuthClientCreateBulk) Save(ctx context.Context) ([]*OAuthClient, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthClient, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthClientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthClientCreateBulk) SaveX(ctx context.Context) []*OAuthClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthClientCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthClientCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
