// Code generated by ent, DO NOT EDIT.

package _test

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/haakco/mcp-kit/entschema/_test/oauthauthorizationcode"
)

// OAuthAuthorizationCode is the model entity for the OAuthAuthorizationCode schema.
type OAuthAuthorizationCode struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Type: authorization_code, access_token, refresh_token, pkce, oidc
	SessionType string `json:"session_type,omitempty"`
	// Unique token/code signature for lookup
	Signature string `json:"signature,omitempty"`
	// OAuth client ID that owns this session
	ClientID string `json:"client_id,omitempty"`
	// Optional consumer user ID
	UserID *int `json:"user_id,omitempty"`
	// Fosite request ID for token revocation
	RequestID string `json:"request_id,omitempty"`
	// Space-separated granted scopes
	Scopes string `json:"scopes,omitempty"`
	// Serialized Fosite session data
	SessionData map[string]interface{} `json:"session_data,omitempty"`
	// Whether this session is still valid
	Active bool `json:"active,omitempty"`
	// When this session expires
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// When Fosite created the original request
	RequestedAt  *time.Time `json:"requested_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuthAuthorizationCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauthauthorizationcode.FieldSessionData:
			values[i] = new([]byte)
		case oauthauthorizationcode.FieldActive:
			values[i] = new(sql.NullBool)
		case oauthauthorizationcode.FieldID, oauthauthorizationcode.FieldUserID:
			values[i] = new(sql.NullInt64)
		case oauthauthorizationcode.FieldSessionType, oauthauthorizationcode.FieldSignature, oauthauthorizationcode.FieldClientID, oauthauthorizationcode.FieldRequestID, oauthauthorizationcode.FieldScopes:
			values[i] = new(sql.NullString)
		case oauthauthorizationcode.FieldExpiresAt, oauthauthorizationcode.FieldRequestedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuthAuthorizationCode fields.
func (_m *OAuthAuthorizationCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauthauthorizationcode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case oauthauthorizationcode.FieldSessionType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_type", values[i])
			} else if value.Valid {
				_m.SessionType = value.String
			}
		case oauthauthorizationcode.FieldSignature:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field signature", values[i])
			} else if value.Valid {
				_m.Signature = value.String
			}
		case oauthauthorizationcode.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case oauthauthorizationcode.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(int)
				*_m.UserID = int(value.Int64)
			}
		case oauthauthorizationcode.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case oauthauthorizationcode.FieldScopes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scopes", values[i])
			} else if value.Valid {
				_m.Scopes = value.String
			}
		case oauthauthorizationcode.FieldSessionData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field session_data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SessionData); err != nil {
					return fmt.Errorf("unmarshal field session_data: %w", err)
				}
			}
		case oauthauthorizationcode.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case oauthauthorizationcode.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case oauthauthorizationcode.FieldRequestedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field requested_at", values[i])
			} else if value.Valid {
				_m.RequestedAt = new(time.Time)
				*_m.RequestedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuthAuthorizationCode.
// This includes values selected through modifiers, order, etc.
func (_m *OAuthAuthorizationCode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OAuthAuthorizationCode.
// Note that you need to call OAuthAuthorizationCode.Unwrap() before calling this method if this OAuthAuthorizationCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuthAuthorizationCode) Update() *OAuthAuthorizationCodeUpdateOne {
	return NewOAuthAuthorizationCodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuthAuthorizationCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuthAuthorizationCode) Unwrap() *OAuthAuthorizationCode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("_test: OAuthAuthorizationCode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuthAuthorizationCode) String() string {
	var builder strings.Builder
	builder.WriteString("OAuthAuthorizationCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_type=")
	builder.WriteString(_m.SessionType)
	builder.WriteString(", ")
	builder.WriteString("signature=")
	builder.WriteString(_m.Signature)
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("scopes=")
	builder.WriteString(_m.Scopes)
	builder.WriteString(", ")
	builder.WriteString("session_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionData))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RequestedAt; v != nil {
		builder.WriteString("requested_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// OAuthAuthorizationCodes is a parsable slice of OAuthAuthorizationCode.
type OAuthAuthorizationCodes []*OAuthAuthorizationCode
