// Code generated by ent, DO NOT EDIT.

package _test

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/haakco/mcp-kit/entschema/_test/oauthsigningkey"
	"github.com/haakco/mcp-kit/entschema/_test/predicate"
)

// OAuthSigningKeyDelete is the builder for deleting a OAuthSigningKey entity.
type OAuthSigningKeyDelete struct {
	config
	hooks    []Hook
	mutation *OAuthSigningKeyMutation
}

// Where appends a list predicates to the OAuthSigningKeyDelete builder.
func (_d *OAuthSigningKeyDelete) Where(ps ...predicate.OAuthSigningKey) *OAuthSigningKeyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OAuthSigningKeyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OAuthSigningKeyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OAuthSigningKeyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(oauthsigningkey.Table, sqlgraph.NewFieldSpec(oauthsigningkey.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OAuthSigningKeyDeleteOne is the builder for deleting a single OAuthSigningKey entity.
type OAuthSigningKeyDeleteOne struct {
	_d *OAuthSigningKeyDelete
}

// Where appends a list predicates to the OAuthSigningKeyDelete builder.
func (_d *OAuthSigningKeyDeleteOne) Where(ps ...predicate.OAuthSigningKey) *OAuthSigningKeyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OAuthSigningKeyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{oauthsigningkey.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OAuthSigningKeyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
