// Code generated by ent, DO NOT EDIT.

package _test

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/haakco/mcp-kit/entschema/_test/personalaccesstoken"
)

// PersonalAccessTokenCreate is the builder for creating a PersonalAccessToken entity.
type PersonalAccessTokenCreate struct {
	config
	mutation *PersonalAccessTokenMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *PersonalAccessTokenCreate) SetUserID(v int) *PersonalAccessTokenCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *PersonalAccessTokenCreate) SetName(v string) *PersonalAccessTokenCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *PersonalAccessTokenCreate) SetTokenHash(v string) *PersonalAccessTokenCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetTokenPrefix sets the "token_prefix" field.
func (_c *PersonalAccessTokenCreate) SetTokenPrefix(v string) *PersonalAccessTokenCreate {
	_c.mutation.SetTokenPrefix(v)
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *PersonalAccessTokenCreate) SetLastUsedAt(v time.Time) *PersonalAccessTokenCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *PersonalAccessTokenCreate) SetNillableLastUsedAt(v *time.Time) *PersonalAccessTokenCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *PersonalAccessTokenCreate) SetExpiresAt(v time.Time) *PersonalAccessTokenCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *PersonalAccessTokenCreate) SetNillableExpiresAt(v *time.Time) *PersonalAccessTokenCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// Mutation returns the PersonalAccessTokenMutation object of the builder.
func (_c *PersonalAccessTokenCreate) Mutation() *PersonalAccessTokenMutation {
	return _c.mutation
}

// Save creates the PersonalAccessToken in the database.
func (_c *PersonalAccessTokenCreate) Save(ctx context.Context) (*PersonalAccessToken, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PersonalAccessTokenCreate) SaveX(ctx context.Context) *PersonalAccessToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PersonalAccessTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PersonalAccessTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PersonalAccessTokenCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`_test: missing required field "PersonalAccessToken.user_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`_test: missing required field "PersonalAccessToken.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := personalaccesstoken.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`_test: validator failed for field "PersonalAccessToken.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`_test: missing required field "PersonalAccessToken.token_hash"`)}
	}
	if v, ok := _c.mutation.TokenHash(); ok {
		if err := personalaccesstoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`_test: validator failed for field "PersonalAccessToken.token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenPrefix(); !ok {
		return &ValidationError{Name: "token_prefix", err: errors.New(`_test: missing required field "PersonalAccessToken.token_prefix"`)}
	}
	if v, ok := _c.mutation.TokenPrefix(); ok {
		if err := personalaccesstoken.TokenPrefixValidator(v); err != nil {
			return &ValidationError{Name: "token_prefix", err: fmt.Errorf(`_test: validator failed for field "PersonalAccessToken.token_prefix": %w`, err)}
		}
	}
	return nil
}

func (_c *PersonalAccessTokenCreate) sqlSave(ctx context.Context) (*PersonalAccessToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PersonalAccessTokenCreate) createSpec() (*PersonalAccessToken, *sqlgraph.CreateSpec) {
	var (
		_node = &PersonalAccessToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(personalaccesstoken.Table, sqlgraph.NewFieldSpec(personalaccesstoken.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(personalaccesstoken.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(personalaccesstoken.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(personalaccesstoken.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.TokenPrefix(); ok {
		_spec.SetField(personalaccesstoken.FieldTokenPrefix, field.TypeString, value)
		_node.TokenPrefix = value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(personalaccesstoken.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(personalaccesstoken.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	return _node, _spec
}

// PersonalAccessTokenCreateBulk is the builder for creating many PersonalAccessToken entities in bulk.
type PersonalAccessTokenCreateBulk struct {
	config
	err      error
	builders []*PersonalAccessTokenCreate
}

// Save creates the PersonalAccessToken entities in the database.
func (_c *PersonalAccessTokenCreateBulk) Save(ctx context.Context) ([]*PersonalAccessToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PersonalAccessToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PersonalAccessTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PersonalAccessTokenCreateBulk) SaveX(ctx context.Context) []*PersonalAccessToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PersonalAccessTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PersonalAccessTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
