// Code generated by ent, DO NOT EDIT.

package _test

import (
	"github.com/haakco/mcp-kit/entschema/_test/oauthaccesstoken"
	"github.com/haakco/mcp-kit/entschema/_test/oauthauthorizationcode"
	"github.com/haakco/mcp-kit/entschema/_test/oauthclient"
	"github.com/haakco/mcp-kit/entschema/_test/oauthrefreshtoken"
	"github.com/haakco/mcp-kit/entschema/_test/oauthsigningkey"
	"github.com/haakco/mcp-kit/entschema/_test/personalaccesstoken"
	"github.com/haakco/mcp-kit/entschema/_test/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	oauthaccesstokenMixin := schema.OAuthAccessToken{}.Mixin()
	oauthaccesstokenMixinFields0 := oauthaccesstokenMixin[0].Fields()
	_ = oauthaccesstokenMixinFields0
	oauthaccesstokenFields := schema.OAuthAccessToken{}.Fields()
	_ = oauthaccesstokenFields
	// oauthaccesstokenDescSessionType is the schema descriptor for session_type field.
	oauthaccesstokenDescSessionType := oauthaccesstokenMixinFields0[0].Descriptor()
	// oauthaccesstoken.SessionTypeValidator is a validator for the "session_type" field. It is called by the builders before save.
	oauthaccesstoken.SessionTypeValidator = func() func(string) error {
		validators := oauthaccesstokenDescSessionType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(session_type string) error {
			for _, fn := range fns {
				if err := fn(session_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauthaccesstokenDescSignature is the schema descriptor for signature field.
	oauthaccesstokenDescSignature := oauthaccesstokenMixinFields0[1].Descriptor()
	// oauthaccesstoken.SignatureValidator is a validator for the "signature" field. It is called by the builders before save.
	oauthaccesstoken.SignatureValidator = func() func(string) error {
		validators := oauthaccesstokenDescSignature.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(signature string) error {
			for _, fn := range fns {
				if err := fn(signature); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauthaccesstokenDescClientID is the schema descriptor for client_id field.
	oauthaccesstokenDescClientID := oauthaccesstokenMixinFields0[2].Descriptor()
	// oauthaccesstoken.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauthaccesstoken.ClientIDValidator = func() func(string) error {
		validators := oauthaccesstokenDescClientID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(client_id string) error {
			for _, fn := range fns {
				if err := fn(client_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauthaccesstokenDescRequestID is the schema descriptor for request_id field.
	oauthaccesstokenDescRequestID := oauthaccesstokenMixinFields0[4].Descriptor()
	// oauthaccesstoken.DefaultRequestID holds the default value on creation for the request_id field.
	oauthaccesstoken.DefaultRequestID = oauthaccesstokenDescRequestID.Default.(string)
	// oauthaccesstoken.RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	oauthaccesstoken.RequestIDValidator = oauthaccesstokenDescRequestID.Validators[0].(func(string) error)
	// oauthaccesstokenDescScopes is the schema descriptor for scopes field.
	oauthaccesstokenDescScopes := oauthaccesstokenMixinFields0[5].Descriptor()
	// oauthaccesstoken.DefaultScopes holds the default value on creation for the scopes field.
	oauthaccesstoken.DefaultScopes = oauthaccesstokenDescScopes.Default.(string)
	// oauthaccesstoken.ScopesValidator is a validator for the "scopes" field. It is called by the builders before save.
	oauthaccesstoken.ScopesValidator = oauthaccesstokenDescScopes.Validators[0].(func(string) error)
	// oauthaccesstokenDescSessionData is the schema descriptor for session_data field.
	oauthaccesstokenDescSessionData := oauthaccesstokenMixinFields0[6].Descriptor()
	// oauthaccesstoken.DefaultSessionData holds the default value on creation for the session_data field.
	oauthaccesstoken.DefaultSessionData = oauthaccesstokenDescSessionData.Default.(map[string]interface{})
	// oauthaccesstokenDescActive is the schema descriptor for active field.
	oauthaccesstokenDescActive := oauthaccesstokenMixinFields0[7].Descriptor()
	// oauthaccesstoken.DefaultActive holds the default value on creation for the active field.
	oauthaccesstoken.DefaultActive = oauthaccesstokenDescActive.Default.(bool)
	oauthauthorizationcodeMixin := schema.OAuthAuthorizationCode{}.Mixin()
	oauthauthorizationcodeMixinFields0 := oauthauthorizationcodeMixin[0].Fields()
	_ = oauthauthorizationcodeMixinFields0
	oauthauthorizationcodeFields := schema.OAuthAuthorizationCode{}.Fields()
	_ = oauthauthorizationcodeFields
	// oauthauthorizationcodeDescSessionType is the schema descriptor for session_type field.
	oauthauthorizationcodeDescSessionType := oauthauthorizationcodeMixinFields0[0].Descriptor()
	// oauthauthorizationcode.SessionTypeValidator is a validator for the "session_type" field. It is called by the builders before save.
	oauthauthorizationcode.SessionTypeValidator = func() func(string) error {
		validators := oauthauthorizationcodeDescSessionType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(session_type string) error {
			for _, fn := range fns {
				if err := fn(session_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauthauthorizationcodeDescSignature is the schema descriptor for signature field.
	oauthauthorizationcodeDescSignature := oauthauthorizationcodeMixinFields0[1].Descriptor()
	// oauthauthorizationcode.SignatureValidator is a validator for the "signature" field. It is called by the builders before save.
	oauthauthorizationcode.SignatureValidator = func() func(string) error {
		validators := oauthauthorizationcodeDescSignature.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(signature string) error {
			for _, fn := range fns {
				if err := fn(signature); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauthauthorizationcodeDescClientID is the schema descriptor for client_id field.
	oauthauthorizationcodeDescClientID := oauthauthorizationcodeMixinFields0[2].Descriptor()
	// oauthauthorizationcode.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauthauthorizationcode.ClientIDValidator = func() func(string) error {
		validators := oauthauthorizationcodeDescClientID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(client_id string) error {
			for _, fn := range fns {
				if err := fn(client_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauthauthorizationcodeDescRequestID is the schema descriptor for request_id field.
	oauthauthorizationcodeDescRequestID := oauthauthorizationcodeMixinFields0[4].Descriptor()
	// oauthauthorizationcode.DefaultRequestID holds the default value on creation for the request_id field.
	oauthauthorizationcode.DefaultRequestID = oauthauthorizationcodeDescRequestID.Default.(string)
	// oauthauthorizationcode.RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	oauthauthorizationcode.RequestIDValidator = oauthauthorizationcodeDescRequestID.Validators[0].(func(string) error)
	// oauthauthorizationcodeDescScopes is the schema descriptor for scopes field.
	oauthauthorizationcodeDescScopes := oauthauthorizationcodeMixinFields0[5].Descriptor()
	// oauthauthorizationcode.DefaultScopes holds the default value on creation for the scopes field.
	oauthauthorizationcode.DefaultScopes = oauthauthorizationcodeDescScopes.Default.(string)
	// oauthauthorizationcode.ScopesValidator is a validator for the "scopes" field. It is called by the builders before save.
	oauthauthorizationcode.ScopesValidator = oauthauthorizationcodeDescScopes.Validators[0].(func(string) error)
	// oauthauthorizationcodeDescSessionData is the schema descriptor for session_data field.
	oauthauthorizationcodeDescSessionData := oauthauthorizationcodeMixinFields0[6].Descriptor()
	// oauthauthorizationcode.DefaultSessionData holds the default value on creation for the session_data field.
	oauthauthorizationcode.DefaultSessionData = oauthauthorizationcodeDescSessionData.Default.(map[string]interface{})
	// oauthauthorizationcodeDescActive is the schema descriptor for active field.
	oauthauthorizationcodeDescActive := oauthauthorizationcodeMixinFields0[7].Descriptor()
	// oauthauthorizationcode.DefaultActive holds the default value on creation for the active field.
	oauthauthorizationcode.DefaultActive = oauthauthorizationcodeDescActive.Default.(bool)
	oauthclientMixin := schema.OAuthClient{}.Mixin()
	oauthclientMixinFields0 := oauthclientMixin[0].Fields()
	_ = oauthclientMixinFields0
	oauthclientFields := schema.OAuthClient{}.Fields()
	_ = oauthclientFields
	// oauthclientDescClientID is the schema descriptor for client_id field.
	oauthclientDescClientID := oauthclientMixinFields0[0].Descriptor()
	// oauthclient.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauthclient.ClientIDValidator = func() func(string) error {
		validators := oauthclientDescClientID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(client_id string) error {
			for _, fn := range fns {
				if err := fn(client_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauthclientDescClientSecretHash is the schema descriptor for client_secret_hash field.
	oauthclientDescClientSecretHash := oauthclientMixinFields0[1].Descriptor()
	// oauthclient.DefaultClientSecretHash holds the default value on creation for the client_secret_hash field.
	oauthclient.DefaultClientSecretHash = oauthclientDescClientSecretHash.Default.(string)
	// oauthclientDescRedirectUris is the schema descriptor for redirect_uris field.
	oauthclientDescRedirectUris := oauthclientMixinFields0[2].Descriptor()
	// oauthclient.DefaultRedirectUris holds the default value on creation for the redirect_uris field.
	oauthclient.DefaultRedirectUris = oauthclientDescRedirectUris.Default.([]string)
	// oauthclientDescGrantTypes is the schema descriptor for grant_types field.
	oauthclientDescGrantTypes := oauthclientMixinFields0[3].Descriptor()
	// oauthclient.DefaultGrantTypes holds the default value on creation for the grant_types field.
	oauthclient.DefaultGrantTypes = oauthclientDescGrantTypes.Default.([]string)
	// oauthclientDescResponseTypes is the schema descriptor for response_types field.
	oauthclientDescResponseTypes := oauthclientMixinFields0[4].Descriptor()
	// oauthclient.DefaultResponseTypes holds the default value on creation for the response_types field.
	oauthclient.DefaultResponseTypes = oauthclientDescResponseTypes.Default.([]string)
	// oauthclientDescScopes is the schema descriptor for scopes field.
	oauthclientDescScopes := oauthclientMixinFields0[5].Descriptor()
	// oauthclient.DefaultScopes holds the default value on creation for the scopes field.
	oauthclient.DefaultScopes = oauthclientDescScopes.Default.(string)
	// oauthclient.ScopesValidator is a validator for the "scopes" field. It is called by the builders before save.
	oauthclient.ScopesValidator = oauthclientDescScopes.Validators[0].(func(string) error)
	// oauthclientDescIsPublic is the schema descriptor for is_public field.
	oauthclientDescIsPublic := oauthclientMixinFields0[6].Descriptor()
	// oauthclient.DefaultIsPublic holds the default value on creation for the is_public field.
	oauthclient.DefaultIsPublic = oauthclientDescIsPublic.Default.(bool)
	// oauthclientDescName is the schema descriptor for name field.
	oauthclientDescName := oauthclientMixinFields0[7].Descriptor()
	// oauthclient.NameValidator is a validator for the "name" field. It is called by the builders before save.
	oauthclient.NameValidator = func() func(string) error {
		validators := oauthclientDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	oauthrefreshtokenMixin := schema.OAuthRefreshToken{}.Mixin()
	oauthrefreshtokenMixinFields0 := oauthrefreshtokenMixin[0].Fields()
	_ = oauthrefreshtokenMixinFields0
	oauthrefreshtokenFields := schema.OAuthRefreshToken{}.Fields()
	_ = oauthrefreshtokenFields
	// oauthrefreshtokenDescSessionType is the schema descriptor for session_type field.
	oauthrefreshtokenDescSessionType := oauthrefreshtokenMixinFields0[0].Descriptor()
	// oauthrefreshtoken.SessionTypeValidator is a validator for the "session_type" field. It is called by the builders before save.
	oauthrefreshtoken.SessionTypeValidator = func() func(string) error {
		validators := oauthrefreshtokenDescSessionType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(session_type string) error {
			for _, fn := range fns {
				if err := fn(session_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauthrefreshtokenDescSignature is the schema descriptor for signature field.
	oauthrefreshtokenDescSignature := oauthrefreshtokenMixinFields0[1].Descriptor()
	// oauthrefreshtoken.SignatureValidator is a validator for the "signature" field. It is called by the builders before save.
	oauthrefreshtoken.SignatureValidator = func() func(string) error {
		validators := oauthrefreshtokenDescSignature.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(signature string) error {
			for _, fn := range fns {
				if err := fn(signature); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauthrefreshtokenDescClientID is the schema descriptor for client_id field.
	oauthrefreshtokenDescClientID := oauthrefreshtokenMixinFields0[2].Descriptor()
	// oauthrefreshtoken.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauthrefreshtoken.ClientIDValidator = func() func(string) error {
		validators := oauthrefreshtokenDescClientID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(client_id string) error {
			for _, fn := range fns {
				if err := fn(client_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauthrefreshtokenDescRequestID is the schema descriptor for request_id field.
	oauthrefreshtokenDescRequestID := oauthrefreshtokenMixinFields0[4].Descriptor()
	// oauthrefreshtoken.DefaultRequestID holds the default value on creation for the request_id field.
	oauthrefreshtoken.DefaultRequestID = oauthrefreshtokenDescRequestID.Default.(string)
	// oauthrefreshtoken.RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	oauthrefreshtoken.RequestIDValidator = oauthrefreshtokenDescRequestID.Validators[0].(func(string) error)
	// oauthrefreshtokenDescScopes is the schema descriptor for scopes field.
	oauthrefreshtokenDescScopes := oauthrefreshtokenMixinFields0[5].Descriptor()
	// oauthrefreshtoken.DefaultScopes holds the default value on creation for the scopes field.
	oauthrefreshtoken.DefaultScopes = oauthrefreshtokenDescScopes.Default.(string)
	// oauthrefreshtoken.ScopesValidator is a validator for the "scopes" field. It is called by the builders before save.
	oauthrefreshtoken.ScopesValidator = oauthrefreshtokenDescScopes.Validators[0].(func(string) error)
	// oauthrefreshtokenDescSessionData is the schema descriptor for session_data field.
	oauthrefreshtokenDescSessionData := oauthrefreshtokenMixinFields0[6].Descriptor()
	// oauthrefreshtoken.DefaultSessionData holds the default value on creation for the session_data field.
	oauthrefreshtoken.DefaultSessionData = oauthrefreshtokenDescSessionData.Default.(map[string]interface{})
	// oauthrefreshtokenDescActive is the schema descriptor for active field.
	oauthrefreshtokenDescActive := oauthrefreshtokenMixinFields0[7].Descriptor()
	// oauthrefreshtoken.DefaultActive holds the default value on creation for the active field.
	oauthrefreshtoken.DefaultActive = oauthrefreshtokenDescActive.Default.(bool)
	oauthsigningkeyMixin := schema.OAuthSigningKey{}.Mixin()
	oauthsigningkeyMixinFields0 := oauthsigningkeyMixin[0].Fields()
	_ = oauthsigningkeyMixinFields0
	oauthsigningkeyFields := schema.OAuthSigningKey{}.Fields()
	_ = oauthsigningkeyFields
	// oauthsigningkeyDescKid is the schema descriptor for kid field.
	oauthsigningkeyDescKid := oauthsigningkeyMixinFields0[0].Descriptor()
	// oauthsigningkey.KidValidator is a validator for the "kid" field. It is called by the builders before save.
	oauthsigningkey.KidValidator = func() func(string) error {
		validators := oauthsigningkeyDescKid.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(kid string) error {
			for _, fn := range fns {
				if err := fn(kid); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauthsigningkeyDescAlgorithm is the schema descriptor for algorithm field.
	oauthsigningkeyDescAlgorithm := oauthsigningkeyMixinFields0[1].Descriptor()
	// oauthsigningkey.DefaultAlgorithm holds the default value on creation for the algorithm field.
	oauthsigningkey.DefaultAlgorithm = oauthsigningkeyDescAlgorithm.Default.(string)
	// oauthsigningkey.AlgorithmValidator is a validator for the "algorithm" field. It is called by the builders before save.
	oauthsigningkey.AlgorithmValidator = oauthsigningkeyDescAlgorithm.Validators[0].(func(string) error)
	// oauthsigningkeyDescIsActive is the schema descriptor for is_active field.
	oauthsigningkeyDescIsActive := oauthsigningkeyMixinFields0[4].Descriptor()
	// oauthsigningkey.DefaultIsActive holds the default value on creation for the is_active field.
	oauthsigningkey.DefaultIsActive = oauthsigningkeyDescIsActive.Default.(bool)
	personalaccesstokenMixin := schema.PersonalAccessToken{}.Mixin()
	personalaccesstokenMixinFields0 := personalaccesstokenMixin[0].Fields()
	_ = personalaccesstokenMixinFields0
	personalaccesstokenFields := schema.PersonalAccessToken{}.Fields()
	_ = personalaccesstokenFields
	// personalaccesstokenDescName is the schema descriptor for name field.
	personalaccesstokenDescName := personalaccesstokenMixinFields0[1].Descriptor()
	// personalaccesstoken.NameValidator is a validator for the "name" field. It is called by the builders before save.
	personalaccesstoken.NameValidator = func() func(string) error {
		validators := personalaccesstokenDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// personalaccesstokenDescTokenHash is the schema descriptor for token_hash field.
	personalaccesstokenDescTokenHash := personalaccesstokenMixinFields0[2].Descriptor()
	// personalaccesstoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	personalaccesstoken.TokenHashValidator = func() func(string) error {
		validators := personalaccesstokenDescTokenHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(token_hash string) error {
			for _, fn := range fns {
				if err := fn(token_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// personalaccesstokenDescTokenPrefix is the schema descriptor for token_prefix field.
	personalaccesstokenDescTokenPrefix := personalaccesstokenMixinFields0[3].Descriptor()
	// personalaccesstoken.TokenPrefixValidator is a validator for the "token_prefix" field. It is called by the builders before save.
	personalaccesstoken.TokenPrefixValidator = func() func(string) error {
		validators := personalaccesstokenDescTokenPrefix.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(token_prefix string) error {
			for _, fn := range fns {
				if err := fn(token_prefix); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}
