// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/haakco/mcp-kit/entschema/_test"
)

// The OAuthAccessTokenFunc type is an adapter to allow the use of ordinary
// function as OAuthAccessToken mutator.
type OAuthAccessTokenFunc func(context.Context, *_test.OAuthAccessTokenMutation) (_test.Value, error)

// Mutate calls f(ctx, m).
func (f OAuthAccessTokenFunc) Mutate(ctx context.Context, m _test.Mutation) (_test.Value, error) {
	if mv, ok := m.(*_test.OAuthAccessTokenMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *_test.OAuthAccessTokenMutation", m)
}

// The OAuthAuthorizationCodeFunc type is an adapter to allow the use of ordinary
// function as OAuthAuthorizationCode mutator.
type OAuthAuthorizationCodeFunc func(context.Context, *_test.OAuthAuthorizationCodeMutation) (_test.Value, error)

// Mutate calls f(ctx, m).
func (f OAuthAuthorizationCodeFunc) Mutate(ctx context.Context, m _test.Mutation) (_test.Value, error) {
	if mv, ok := m.(*_test.OAuthAuthorizationCodeMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *_test.OAuthAuthorizationCodeMutation", m)
}

// The OAuthClientFunc type is an adapter to allow the use of ordinary
// function as OAuthClient mutator.
type OAuthClientFunc func(context.Context, *_test.OAuthClientMutation) (_test.Value, error)

// Mutate calls f(ctx, m).
func (f OAuthClientFunc) Mutate(ctx context.Context, m _test.Mutation) (_test.Value, error) {
	if mv, ok := m.(*_test.OAuthClientMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *_test.OAuthClientMutation", m)
}

// The OAuthRefreshTokenFunc type is an adapter to allow the use of ordinary
// function as OAuthRefreshToken mutator.
type OAuthRefreshTokenFunc func(context.Context, *_test.OAuthRefreshTokenMutation) (_test.Value, error)

// Mutate calls f(ctx, m).
func (f OAuthRefreshTokenFunc) Mutate(ctx context.Context, m _test.Mutation) (_test.Value, error) {
	if mv, ok := m.(*_test.OAuthRefreshTokenMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *_test.OAuthRefreshTokenMutation", m)
}

// The OAuthSigningKeyFunc type is an adapter to allow the use of ordinary
// function as OAuthSigningKey mutator.
type OAuthSigningKeyFunc func(context.Context, *_test.OAuthSigningKeyMutation) (_test.Value, error)

// Mutate calls f(ctx, m).
func (f OAuthSigningKeyFunc) Mutate(ctx context.Context, m _test.Mutation) (_test.Value, error) {
	if mv, ok := m.(*_test.OAuthSigningKeyMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *_test.OAuthSigningKeyMutation", m)
}

// The PersonalAccessTokenFunc type is an adapter to allow the use of ordinary
// function as PersonalAccessToken mutator.
type PersonalAccessTokenFunc func(context.Context, *_test.PersonalAccessTokenMutation) (_test.Value, error)

// Mutate calls f(ctx, m).
func (f PersonalAccessTokenFunc) Mutate(ctx context.Context, m _test.Mutation) (_test.Value, error) {
	if mv, ok := m.(*_test.PersonalAccessTokenMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *_test.PersonalAccessTokenMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, _test.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m _test.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m _test.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m _test.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op _test.Op) Condition {
	return func(_ context.Context, m _test.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m _test.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m _test.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m _test.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk _test.Hook, cond Condition) _test.Hook {
	return func(next _test.Mutator) _test.Mutator {
		return _test.MutateFunc(func(ctx context.Context, m _test.Mutation) (_test.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, _test.Delete|_test.Create)
func On(hk _test.Hook, op _test.Op) _test.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, _test.Update|_test.UpdateOne)
func Unless(hk _test.Hook, op _test.Op) _test.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) _test.Hook {
	return func(_test.Mutator) _test.Mutator {
		return _test.MutateFunc(func(context.Context, _test.Mutation) (_test.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []_test.Hook {
//		return []_test.Hook{
//			Reject(_test.Delete|_test.Update),
//		}
//	}
func Reject(op _test.Op) _test.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []_test.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ..._test.Hook) Chain {
	return Chain{append([]_test.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() _test.Hook {
	return func(mutator _test.Mutator) _test.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ..._test.Hook) Chain {
	newHooks := make([]_test.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
