// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OauthAccessTokensColumns holds the columns for the "oauth_access_tokens" table.
	OauthAccessTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "session_type", Type: field.TypeString, Size: 32},
		{Name: "signature", Type: field.TypeString, Size: 512},
		{Name: "client_id", Type: field.TypeString, Size: 255},
		{Name: "user_id", Type: field.TypeInt, Nullable: true},
		{Name: "request_id", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "scopes", Type: field.TypeString, Size: 1000, Default: ""},
		{Name: "session_data", Type: field.TypeJSON},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "requested_at", Type: field.TypeTime, Nullable: true},
	}
	// OauthAccessTokensTable holds the schema information for the "oauth_access_tokens" table.
	OauthAccessTokensTable = &schema.Table{
		Name:       "oauth_access_tokens",
		Columns:    OauthAccessTokensColumns,
		PrimaryKey: []*schema.Column{OauthAccessTokensColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthaccesstoken_session_type_signature",
				Unique:  true,
				Columns: []*schema.Column{OauthAccessTokensColumns[1], OauthAccessTokensColumns[2]},
			},
			{
				Name:    "oauthaccesstoken_client_id",
				Unique:  false,
				Columns: []*schema.Column{OauthAccessTokensColumns[3]},
			},
			{
				Name:    "oauthaccesstoken_user_id",
				Unique:  false,
				Columns: []*schema.Column{OauthAccessTokensColumns[4]},
			},
			{
				Name:    "oauthaccesstoken_request_id",
				Unique:  false,
				Columns: []*schema.Column{OauthAccessTokensColumns[5]},
			},
			{
				Name:    "oauthaccesstoken_session_type_active",
				Unique:  false,
				Columns: []*schema.Column{OauthAccessTokensColumns[1], OauthAccessTokensColumns[8]},
			},
		},
	}
	// OauthAuthorizationCodesColumns holds the columns for the "oauth_authorization_codes" table.
	OauthAuthorizationCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "session_type", Type: field.TypeString, Size: 32},
		{Name: "signature", Type: field.TypeString, Size: 512},
		{Name: "client_id", Type: field.TypeString, Size: 255},
		{Name: "user_id", Type: field.TypeInt, Nullable: true},
		{Name: "request_id", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "scopes", Type: field.TypeString, Size: 1000, Default: ""},
		{Name: "session_data", Type: field.TypeJSON},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "requested_at", Type: field.TypeTime, Nullable: true},
	}
	// OauthAuthorizationCodesTable holds the schema information for the "oauth_authorization_codes" table.
	OauthAuthorizationCodesTable = &schema.Table{
		Name:       "oauth_authorization_codes",
		Columns:    OauthAuthorizationCodesColumns,
		PrimaryKey: []*schema.Column{OauthAuthorizationCodesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthauthorizationcode_session_type_signature",
				Unique:  true,
				Columns: []*schema.Column{OauthAuthorizationCodesColumns[1], OauthAuthorizationCodesColumns[2]},
			},
			{
				Name:    "oauthauthorizationcode_client_id",
				Unique:  false,
				Columns: []*schema.Column{OauthAuthorizationCodesColumns[3]},
			},
			{
				Name:    "oauthauthorizationcode_user_id",
				Unique:  false,
				Columns: []*schema.Column{OauthAuthorizationCodesColumns[4]},
			},
			{
				Name:    "oauthauthorizationcode_request_id",
				Unique:  false,
				Columns: []*schema.Column{OauthAuthorizationCodesColumns[5]},
			},
			{
				Name:    "oauthauthorizationcode_session_type_active",
				Unique:  false,
				Columns: []*schema.Column{OauthAuthorizationCodesColumns[1], OauthAuthorizationCodesColumns[8]},
			},
		},
	}
	// OauthClientsColumns holds the columns for the "oauth_clients" table.
	OauthClientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "client_id", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "client_secret_hash", Type: field.TypeString, Default: ""},
		{Name: "redirect_uris", Type: field.TypeJSON},
		{Name: "grant_types", Type: field.TypeJSON},
		{Name: "response_types", Type: field.TypeJSON},
		{Name: "scopes", Type: field.TypeString, Size: 1000, Default: ""},
		{Name: "is_public", Type: field.TypeBool, Default: false},
		{Name: "name", Type: field.TypeString, Size: 200},
		{Name: "workspace_id", Type: field.TypeInt, Nullable: true},
	}
	// OauthClientsTable holds the schema information for the "oauth_clients" table.
	OauthClientsTable = &schema.Table{
		Name:       "oauth_clients",
		Columns:    OauthClientsColumns,
		PrimaryKey: []*schema.Column{OauthClientsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthclient_client_id",
				Unique:  false,
				Columns: []*schema.Column{OauthClientsColumns[1]},
			},
			{
				Name:    "oauthclient_workspace_id",
				Unique:  false,
				Columns: []*schema.Column{OauthClientsColumns[9]},
			},
		},
	}
	// OauthRefreshTokensColumns holds the columns for the "oauth_refresh_tokens" table.
	OauthRefreshTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "session_type", Type: field.TypeString, Size: 32},
		{Name: "signature", Type: field.TypeString, Size: 512},
		{Name: "client_id", Type: field.TypeString, Size: 255},
		{Name: "user_id", Type: field.TypeInt, Nullable: true},
		{Name: "request_id", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "scopes", Type: field.TypeString, Size: 1000, Default: ""},
		{Name: "session_data", Type: field.TypeJSON},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "requested_at", Type: field.TypeTime, Nullable: true},
	}
	// OauthRefreshTokensTable holds the schema information for the "oauth_refresh_tokens" table.
	OauthRefreshTokensTable = &schema.Table{
		Name:       "oauth_refresh_tokens",
		Columns:    OauthRefreshTokensColumns,
		PrimaryKey: []*schema.Column{OauthRefreshTokensColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthrefreshtoken_session_type_signature",
				Unique:  true,
				Columns: []*schema.Column{OauthRefreshTokensColumns[1], OauthRefreshTokensColumns[2]},
			},
			{
				Name:    "oauthrefreshtoken_client_id",
				Unique:  false,
				Columns: []*schema.Column{OauthRefreshTokensColumns[3]},
			},
			{
				Name:    "oauthrefreshtoken_user_id",
				Unique:  false,
				Columns: []*schema.Column{OauthRefreshTokensColumns[4]},
			},
			{
				Name:    "oauthrefreshtoken_request_id",
				Unique:  false,
				Columns: []*schema.Column{OauthRefreshTokensColumns[5]},
			},
			{
				Name:    "oauthrefreshtoken_session_type_active",
				Unique:  false,
				Columns: []*schema.Column{OauthRefreshTokensColumns[1], OauthRefreshTokensColumns[8]},
			},
		},
	}
	// OauthSigningKeysColumns holds the columns for the "oauth_signing_keys" table.
	OauthSigningKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "kid", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "algorithm", Type: field.TypeString, Size: 32, Default: "RS256"},
		{Name: "private_key_pem", Type: field.TypeString, Size: 2147483647},
		{Name: "public_key_pem", Type: field.TypeString, Size: 2147483647},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "retired_at", Type: field.TypeTime, Nullable: true},
	}
	// OauthSigningKeysTable holds the schema information for the "oauth_signing_keys" table.
	OauthSigningKeysTable = &schema.Table{
		Name:       "oauth_signing_keys",
		Columns:    OauthSigningKeysColumns,
		PrimaryKey: []*schema.Column{OauthSigningKeysColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthsigningkey_kid",
				Unique:  false,
				Columns: []*schema.Column{OauthSigningKeysColumns[1]},
			},
			{
				Name:    "oauthsigningkey_is_active",
				Unique:  false,
				Columns: []*schema.Column{OauthSigningKeysColumns[5]},
			},
		},
	}
	// PersonalAccessTokensColumns holds the columns for the "personal_access_tokens" table.
	PersonalAccessTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString, Size: 200},
		{Name: "token_hash", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "token_prefix", Type: field.TypeString, Size: 20},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
	}
	// PersonalAccessTokensTable holds the schema information for the "personal_access_tokens" table.
	PersonalAccessTokensTable = &schema.Table{
		Name:       "personal_access_tokens",
		Columns:    PersonalAccessTokensColumns,
		PrimaryKey: []*schema.Column{PersonalAccessTokensColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "personalaccesstoken_token_prefix",
				Unique:  false,
				Columns: []*schema.Column{PersonalAccessTokensColumns[4]},
			},
			{
				Name:    "personalaccesstoken_user_id",
				Unique:  false,
				Columns: []*schema.Column{PersonalAccessTokensColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OauthAccessTokensTable,
		OauthAuthorizationCodesTable,
		OauthClientsTable,
		OauthRefreshTokensTable,
		OauthSigningKeysTable,
		PersonalAccessTokensTable,
	}
)

func init() {
}
