// Code generated by ent, DO NOT EDIT.

package oauthaccesstoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/haakco/mcp-kit/entschema/_test/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldLTE(FieldID, id))
}

// SessionType applies equality check predicate on the "session_type" field. It's identical to SessionTypeEQ.
func SessionType(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEQ(FieldSessionType, v))
}

// Signature applies equality check predicate on the "signature" field. It's identical to SignatureEQ.
func Signature(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEQ(FieldSignature, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEQ(FieldClientID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEQ(FieldUserID, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEQ(FieldRequestID, v))
}

// Scopes applies equality check predicate on the "scopes" field. It's identical to ScopesEQ.
func Scopes(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEQ(FieldScopes, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEQ(FieldActive, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEQ(FieldExpiresAt, v))
}

// RequestedAt applies equality check predicate on the "requested_at" field. It's identical to RequestedAtEQ.
func RequestedAt(v time.Time) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEQ(FieldRequestedAt, v))
}

// SessionTypeEQ applies the EQ predicate on the "session_type" field.
func SessionTypeEQ(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEQ(FieldSessionType, v))
}

// SessionTypeNEQ applies the NEQ predicate on the "session_type" field.
func SessionTypeNEQ(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNEQ(FieldSessionType, v))
}

// SessionTypeIn applies the In predicate on the "session_type" field.
func SessionTypeIn(vs ...string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldIn(FieldSessionType, vs...))
}

// SessionTypeNotIn applies the NotIn predicate on the "session_type" field.
func SessionTypeNotIn(vs ...string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNotIn(FieldSessionType, vs...))
}

// SessionTypeGT applies the GT predicate on the "session_type" field.
func SessionTypeGT(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldGT(FieldSessionType, v))
}

// SessionTypeGTE applies the GTE predicate on the "session_type" field.
func SessionTypeGTE(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldGTE(FieldSessionType, v))
}

// SessionTypeLT applies the LT predicate on the "session_type" field.
func SessionTypeLT(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldLT(FieldSessionType, v))
}

// SessionTypeLTE applies the LTE predicate on the "session_type" field.
func SessionTypeLTE(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldLTE(FieldSessionType, v))
}

// SessionTypeContains applies the Contains predicate on the "session_type" field.
func SessionTypeContains(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldContains(FieldSessionType, v))
}

// SessionTypeHasPrefix applies the HasPrefix predicate on the "session_type" field.
func SessionTypeHasPrefix(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldHasPrefix(FieldSessionType, v))
}

// SessionTypeHasSuffix applies the HasSuffix predicate on the "session_type" field.
func SessionTypeHasSuffix(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldHasSuffix(FieldSessionType, v))
}

// SessionTypeEqualFold applies the EqualFold predicate on the "session_type" field.
func SessionTypeEqualFold(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEqualFold(FieldSessionType, v))
}

// SessionTypeContainsFold applies the ContainsFold predicate on the "session_type" field.
func SessionTypeContainsFold(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldContainsFold(FieldSessionType, v))
}

// SignatureEQ applies the EQ predicate on the "signature" field.
func SignatureEQ(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEQ(FieldSignature, v))
}

// SignatureNEQ applies the NEQ predicate on the "signature" field.
func SignatureNEQ(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNEQ(FieldSignature, v))
}

// SignatureIn applies the In predicate on the "signature" field.
func SignatureIn(vs ...string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldIn(FieldSignature, vs...))
}

// SignatureNotIn applies the NotIn predicate on the "signature" field.
func SignatureNotIn(vs ...string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNotIn(FieldSignature, vs...))
}

// SignatureGT applies the GT predicate on the "signature" field.
func SignatureGT(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldGT(FieldSignature, v))
}

// SignatureGTE applies the GTE predicate on the "signature" field.
func SignatureGTE(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldGTE(FieldSignature, v))
}

// SignatureLT applies the LT predicate on the "signature" field.
func SignatureLT(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldLT(FieldSignature, v))
}

// SignatureLTE applies the LTE predicate on the "signature" field.
func SignatureLTE(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldLTE(FieldSignature, v))
}

// SignatureContains applies the Contains predicate on the "signature" field.
func SignatureContains(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldContains(FieldSignature, v))
}

// SignatureHasPrefix applies the HasPrefix predicate on the "signature" field.
func SignatureHasPrefix(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldHasPrefix(FieldSignature, v))
}

// SignatureHasSuffix applies the HasSuffix predicate on the "signature" field.
func SignatureHasSuffix(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldHasSuffix(FieldSignature, v))
}

// SignatureEqualFold applies the EqualFold predicate on the "signature" field.
func SignatureEqualFold(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEqualFold(FieldSignature, v))
}

// SignatureContainsFold applies the ContainsFold predicate on the "signature" field.
func SignatureContainsFold(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldContainsFold(FieldSignature, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldContainsFold(FieldClientID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNotNull(FieldUserID))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldContainsFold(FieldRequestID, v))
}

// ScopesEQ applies the EQ predicate on the "scopes" field.
func ScopesEQ(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEQ(FieldScopes, v))
}

// ScopesNEQ applies the NEQ predicate on the "scopes" field.
func ScopesNEQ(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNEQ(FieldScopes, v))
}

// ScopesIn applies the In predicate on the "scopes" field.
func ScopesIn(vs ...string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldIn(FieldScopes, vs...))
}

// ScopesNotIn applies the NotIn predicate on the "scopes" field.
func ScopesNotIn(vs ...string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNotIn(FieldScopes, vs...))
}

// ScopesGT applies the GT predicate on the "scopes" field.
func ScopesGT(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldGT(FieldScopes, v))
}

// ScopesGTE applies the GTE predicate on the "scopes" field.
func ScopesGTE(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldGTE(FieldScopes, v))
}

// ScopesLT applies the LT predicate on the "scopes" field.
func ScopesLT(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldLT(FieldScopes, v))
}

// ScopesLTE applies the LTE predicate on the "scopes" field.
func ScopesLTE(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldLTE(FieldScopes, v))
}

// ScopesContains applies the Contains predicate on the "scopes" field.
func ScopesContains(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldContains(FieldScopes, v))
}

// ScopesHasPrefix applies the HasPrefix predicate on the "scopes" field.
func ScopesHasPrefix(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldHasPrefix(FieldScopes, v))
}

// ScopesHasSuffix applies the HasSuffix predicate on the "scopes" field.
func ScopesHasSuffix(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldHasSuffix(FieldScopes, v))
}

// ScopesEqualFold applies the EqualFold predicate on the "scopes" field.
func ScopesEqualFold(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEqualFold(FieldScopes, v))
}

// ScopesContainsFold applies the ContainsFold predicate on the "scopes" field.
func ScopesContainsFold(v string) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldContainsFold(FieldScopes, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNEQ(FieldActive, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNotNull(FieldExpiresAt))
}

// RequestedAtEQ applies the EQ predicate on the "requested_at" field.
func RequestedAtEQ(v time.Time) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldEQ(FieldRequestedAt, v))
}

// RequestedAtNEQ applies the NEQ predicate on the "requested_at" field.
func RequestedAtNEQ(v time.Time) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNEQ(FieldRequestedAt, v))
}

// RequestedAtIn applies the In predicate on the "requested_at" field.
func RequestedAtIn(vs ...time.Time) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldIn(FieldRequestedAt, vs...))
}

// RequestedAtNotIn applies the NotIn predicate on the "requested_at" field.
func RequestedAtNotIn(vs ...time.Time) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNotIn(FieldRequestedAt, vs...))
}

// RequestedAtGT applies the GT predicate on the "requested_at" field.
func RequestedAtGT(v time.Time) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldGT(FieldRequestedAt, v))
}

// RequestedAtGTE applies the GTE predicate on the "requested_at" field.
func RequestedAtGTE(v time.Time) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldGTE(FieldRequestedAt, v))
}

// RequestedAtLT applies the LT predicate on the "requested_at" field.
func RequestedAtLT(v time.Time) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldLT(FieldRequestedAt, v))
}

// RequestedAtLTE applies the LTE predicate on the "requested_at" field.
func RequestedAtLTE(v time.Time) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldLTE(FieldRequestedAt, v))
}

// RequestedAtIsNil applies the IsNil predicate on the "requested_at" field.
func RequestedAtIsNil() predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldIsNull(FieldRequestedAt))
}

// RequestedAtNotNil applies the NotNil predicate on the "requested_at" field.
func RequestedAtNotNil() predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.FieldNotNull(FieldRequestedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthAccessToken) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthAccessToken) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthAccessToken) predicate.OAuthAccessToken {
	return predicate.OAuthAccessToken(sql.NotPredicates(p))
}
