// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// OAuthAccessToken is the predicate function for oauthaccesstoken builders.
type OAuthAccessToken func(*sql.Selector)

// OAuthAuthorizationCode is the predicate function for oauthauthorizationcode builders.
type OAuthAuthorizationCode func(*sql.Selector)

// OAuthClient is the predicate function for oauthclient builders.
type OAuthClient func(*sql.Selector)

// OAuthRefreshToken is the predicate function for oauthrefreshtoken builders.
type OAuthRefreshToken func(*sql.Selector)

// OAuthSigningKey is the predicate function for oauthsigningkey builders.
type OAuthSigningKey func(*sql.Selector)

// PersonalAccessToken is the predicate function for personalaccesstoken builders.
type PersonalAccessToken func(*sql.Selector)
