// Code generated by ent, DO NOT EDIT.

package oauthsigningkey

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the oauthsigningkey type in the database.
	Label = "oauth_signing_key"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKid holds the string denoting the kid field in the database.
	FieldKid = "kid"
	// FieldAlgorithm holds the string denoting the algorithm field in the database.
	FieldAlgorithm = "algorithm"
	// FieldPrivateKeyPem holds the string denoting the private_key_pem field in the database.
	FieldPrivateKeyPem = "private_key_pem"
	// FieldPublicKeyPem holds the string denoting the public_key_pem field in the database.
	FieldPublicKeyPem = "public_key_pem"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldRetiredAt holds the string denoting the retired_at field in the database.
	FieldRetiredAt = "retired_at"
	// Table holds the table name of the oauthsigningkey in the database.
	Table = "oauth_signing_keys"
)

// Columns holds all SQL columns for oauthsigningkey fields.
var Columns = []string{
	FieldID,
	FieldKid,
	FieldAlgorithm,
	FieldPrivateKeyPem,
	FieldPublicKeyPem,
	FieldIsActive,
	FieldExpiresAt,
	FieldRetiredAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// KidValidator is a validator for the "kid" field. It is called by the builders before save.
	KidValidator func(string) error
	// DefaultAlgorithm holds the default value on creation for the "algorithm" field.
	DefaultAlgorithm string
	// AlgorithmValidator is a validator for the "algorithm" field. It is called by the builders before save.
	AlgorithmValidator func(string) error
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
)

// OrderOption defines the ordering options for the OAuthSigningKey queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKid orders the results by the kid field.
func ByKid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKid, opts...).ToFunc()
}

// ByAlgorithm orders the results by the algorithm field.
func ByAlgorithm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlgorithm, opts...).ToFunc()
}

// ByPrivateKeyPem orders the results by the private_key_pem field.
func ByPrivateKeyPem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrivateKeyPem, opts...).ToFunc()
}

// ByPublicKeyPem orders the results by the public_key_pem field.
func ByPublicKeyPem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicKeyPem, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByRetiredAt orders the results by the retired_at field.
func ByRetiredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetiredAt, opts...).ToFunc()
}
