// Code generated by ent, DO NOT EDIT.

package oauthsigningkey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/haakco/mcp-kit/entschema/_test/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLTE(FieldID, id))
}

// Kid applies equality check predicate on the "kid" field. It's identical to KidEQ.
func Kid(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldKid, v))
}

// Algorithm applies equality check predicate on the "algorithm" field. It's identical to AlgorithmEQ.
func Algorithm(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldAlgorithm, v))
}

// PrivateKeyPem applies equality check predicate on the "private_key_pem" field. It's identical to PrivateKeyPemEQ.
func PrivateKeyPem(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldPrivateKeyPem, v))
}

// PublicKeyPem applies equality check predicate on the "public_key_pem" field. It's identical to PublicKeyPemEQ.
func PublicKeyPem(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldPublicKeyPem, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldIsActive, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldExpiresAt, v))
}

// RetiredAt applies equality check predicate on the "retired_at" field. It's identical to RetiredAtEQ.
func RetiredAt(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldRetiredAt, v))
}

// KidEQ applies the EQ predicate on the "kid" field.
func KidEQ(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldKid, v))
}

// KidNEQ applies the NEQ predicate on the "kid" field.
func KidNEQ(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNEQ(FieldKid, v))
}

// KidIn applies the In predicate on the "kid" field.
func KidIn(vs ...string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldIn(FieldKid, vs...))
}

// KidNotIn applies the NotIn predicate on the "kid" field.
func KidNotIn(vs ...string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNotIn(FieldKid, vs...))
}

// KidGT applies the GT predicate on the "kid" field.
func KidGT(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGT(FieldKid, v))
}

// KidGTE applies the GTE predicate on the "kid" field.
func KidGTE(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGTE(FieldKid, v))
}

// KidLT applies the LT predicate on the "kid" field.
func KidLT(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLT(FieldKid, v))
}

// KidLTE applies the LTE predicate on the "kid" field.
func KidLTE(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLTE(FieldKid, v))
}

// KidContains applies the Contains predicate on the "kid" field.
func KidContains(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldContains(FieldKid, v))
}

// KidHasPrefix applies the HasPrefix predicate on the "kid" field.
func KidHasPrefix(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldHasPrefix(FieldKid, v))
}

// KidHasSuffix applies the HasSuffix predicate on the "kid" field.
func KidHasSuffix(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldHasSuffix(FieldKid, v))
}

// KidEqualFold applies the EqualFold predicate on the "kid" field.
func KidEqualFold(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEqualFold(FieldKid, v))
}

// KidContainsFold applies the ContainsFold predicate on the "kid" field.
func KidContainsFold(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldContainsFold(FieldKid, v))
}

// AlgorithmEQ applies the EQ predicate on the "algorithm" field.
func AlgorithmEQ(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldAlgorithm, v))
}

// AlgorithmNEQ applies the NEQ predicate on the "algorithm" field.
func AlgorithmNEQ(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNEQ(FieldAlgorithm, v))
}

// AlgorithmIn applies the In predicate on the "algorithm" field.
func AlgorithmIn(vs ...string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldIn(FieldAlgorithm, vs...))
}

// AlgorithmNotIn applies the NotIn predicate on the "algorithm" field.
func AlgorithmNotIn(vs ...string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNotIn(FieldAlgorithm, vs...))
}

// AlgorithmGT applies the GT predicate on the "algorithm" field.
func AlgorithmGT(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGT(FieldAlgorithm, v))
}

// AlgorithmGTE applies the GTE predicate on the "algorithm" field.
func AlgorithmGTE(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGTE(FieldAlgorithm, v))
}

// AlgorithmLT applies the LT predicate on the "algorithm" field.
func AlgorithmLT(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLT(FieldAlgorithm, v))
}

// AlgorithmLTE applies the LTE predicate on the "algorithm" field.
func AlgorithmLTE(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLTE(FieldAlgorithm, v))
}

// AlgorithmContains applies the Contains predicate on the "algorithm" field.
func AlgorithmContains(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldContains(FieldAlgorithm, v))
}

// AlgorithmHasPrefix applies the HasPrefix predicate on the "algorithm" field.
func AlgorithmHasPrefix(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldHasPrefix(FieldAlgorithm, v))
}

// AlgorithmHasSuffix applies the HasSuffix predicate on the "algorithm" field.
func AlgorithmHasSuffix(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldHasSuffix(FieldAlgorithm, v))
}

// AlgorithmEqualFold applies the EqualFold predicate on the "algorithm" field.
func AlgorithmEqualFold(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEqualFold(FieldAlgorithm, v))
}

// AlgorithmContainsFold applies the ContainsFold predicate on the "algorithm" field.
func AlgorithmContainsFold(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldContainsFold(FieldAlgorithm, v))
}

// PrivateKeyPemEQ applies the EQ predicate on the "private_key_pem" field.
func PrivateKeyPemEQ(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldPrivateKeyPem, v))
}

// PrivateKeyPemNEQ applies the NEQ predicate on the "private_key_pem" field.
func PrivateKeyPemNEQ(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNEQ(FieldPrivateKeyPem, v))
}

// PrivateKeyPemIn applies the In predicate on the "private_key_pem" field.
func PrivateKeyPemIn(vs ...string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldIn(FieldPrivateKeyPem, vs...))
}

// PrivateKeyPemNotIn applies the NotIn predicate on the "private_key_pem" field.
func PrivateKeyPemNotIn(vs ...string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNotIn(FieldPrivateKeyPem, vs...))
}

// PrivateKeyPemGT applies the GT predicate on the "private_key_pem" field.
func PrivateKeyPemGT(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGT(FieldPrivateKeyPem, v))
}

// PrivateKeyPemGTE applies the GTE predicate on the "private_key_pem" field.
func PrivateKeyPemGTE(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGTE(FieldPrivateKeyPem, v))
}

// PrivateKeyPemLT applies the LT predicate on the "private_key_pem" field.
func PrivateKeyPemLT(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLT(FieldPrivateKeyPem, v))
}

// PrivateKeyPemLTE applies the LTE predicate on the "private_key_pem" field.
func PrivateKeyPemLTE(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLTE(FieldPrivateKeyPem, v))
}

// PrivateKeyPemContains applies the Contains predicate on the "private_key_pem" field.
func PrivateKeyPemContains(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldContains(FieldPrivateKeyPem, v))
}

// PrivateKeyPemHasPrefix applies the HasPrefix predicate on the "private_key_pem" field.
func PrivateKeyPemHasPrefix(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldHasPrefix(FieldPrivateKeyPem, v))
}

// PrivateKeyPemHasSuffix applies the HasSuffix predicate on the "private_key_pem" field.
func PrivateKeyPemHasSuffix(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldHasSuffix(FieldPrivateKeyPem, v))
}

// PrivateKeyPemEqualFold applies the EqualFold predicate on the "private_key_pem" field.
func PrivateKeyPemEqualFold(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEqualFold(FieldPrivateKeyPem, v))
}

// PrivateKeyPemContainsFold applies the ContainsFold predicate on the "private_key_pem" field.
func PrivateKeyPemContainsFold(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldContainsFold(FieldPrivateKeyPem, v))
}

// PublicKeyPemEQ applies the EQ predicate on the "public_key_pem" field.
func PublicKeyPemEQ(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldPublicKeyPem, v))
}

// PublicKeyPemNEQ applies the NEQ predicate on the "public_key_pem" field.
func PublicKeyPemNEQ(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNEQ(FieldPublicKeyPem, v))
}

// PublicKeyPemIn applies the In predicate on the "public_key_pem" field.
func PublicKeyPemIn(vs ...string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldIn(FieldPublicKeyPem, vs...))
}

// PublicKeyPemNotIn applies the NotIn predicate on the "public_key_pem" field.
func PublicKeyPemNotIn(vs ...string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNotIn(FieldPublicKeyPem, vs...))
}

// PublicKeyPemGT applies the GT predicate on the "public_key_pem" field.
func PublicKeyPemGT(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGT(FieldPublicKeyPem, v))
}

// PublicKeyPemGTE applies the GTE predicate on the "public_key_pem" field.
func PublicKeyPemGTE(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGTE(FieldPublicKeyPem, v))
}

// PublicKeyPemLT applies the LT predicate on the "public_key_pem" field.
func PublicKeyPemLT(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLT(FieldPublicKeyPem, v))
}

// PublicKeyPemLTE applies the LTE predicate on the "public_key_pem" field.
func PublicKeyPemLTE(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLTE(FieldPublicKeyPem, v))
}

// PublicKeyPemContains applies the Contains predicate on the "public_key_pem" field.
func PublicKeyPemContains(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldContains(FieldPublicKeyPem, v))
}

// PublicKeyPemHasPrefix applies the HasPrefix predicate on the "public_key_pem" field.
func PublicKeyPemHasPrefix(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldHasPrefix(FieldPublicKeyPem, v))
}

// PublicKeyPemHasSuffix applies the HasSuffix predicate on the "public_key_pem" field.
func PublicKeyPemHasSuffix(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldHasSuffix(FieldPublicKeyPem, v))
}

// PublicKeyPemEqualFold applies the EqualFold predicate on the "public_key_pem" field.
func PublicKeyPemEqualFold(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEqualFold(FieldPublicKeyPem, v))
}

// PublicKeyPemContainsFold applies the ContainsFold predicate on the "public_key_pem" field.
func PublicKeyPemContainsFold(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldContainsFold(FieldPublicKeyPem, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNEQ(FieldIsActive, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNotNull(FieldExpiresAt))
}

// RetiredAtEQ applies the EQ predicate on the "retired_at" field.
func RetiredAtEQ(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldRetiredAt, v))
}

// RetiredAtNEQ applies the NEQ predicate on the "retired_at" field.
func RetiredAtNEQ(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNEQ(FieldRetiredAt, v))
}

// RetiredAtIn applies the In predicate on the "retired_at" field.
func RetiredAtIn(vs ...time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldIn(FieldRetiredAt, vs...))
}

// RetiredAtNotIn applies the NotIn predicate on the "retired_at" field.
func RetiredAtNotIn(vs ...time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNotIn(FieldRetiredAt, vs...))
}

// RetiredAtGT applies the GT predicate on the "retired_at" field.
func RetiredAtGT(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGT(FieldRetiredAt, v))
}

// RetiredAtGTE applies the GTE predicate on the "retired_at" field.
func RetiredAtGTE(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGTE(FieldRetiredAt, v))
}

// RetiredAtLT applies the LT predicate on the "retired_at" field.
func RetiredAtLT(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLT(FieldRetiredAt, v))
}

// RetiredAtLTE applies the LTE predicate on the "retired_at" field.
func RetiredAtLTE(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLTE(FieldRetiredAt, v))
}

// RetiredAtIsNil applies the IsNil predicate on the "retired_at" field.
func RetiredAtIsNil() predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldIsNull(FieldRetiredAt))
}

// RetiredAtNotNil applies the NotNil predicate on the "retired_at" field.
func RetiredAtNotNil() predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNotNull(FieldRetiredAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthSigningKey) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthSigningKey) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthSigningKey) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.NotPredicates(p))
}
